
-- Topic 2: Fitnesz (Fitness) - 50 English translations (IDs 151-200)
INSERT INTO question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c) VALUES
('fitnesz_151', 'en', 'What is the ideal rest time between strength training sets?', '10 seconds', '60-90 seconds', '5 minutes'),
('fitnesz_152', 'en', 'Which exercise best develops the chest muscles?', 'Squats', 'Bench press', 'Deadlift'),
('fitnesz_153', 'en', 'What is HIIT training?', 'Low intensity workout', 'High intensity interval training', 'Stretching'),
('fitnesz_154', 'en', 'How many times per week should you train the same muscle group?', '1', '2-3', '7'),
('fitnesz_155', 'en', 'What is progressive overload?', 'Decreasing weight', 'Gradually increasing training load', 'Rest'),
('fitnesz_156', 'en', 'Which exercise targets the quadriceps?', 'Pull-ups', 'Squats', 'Bench press'),
('fitnesz_157', 'en', 'What is the recommended warm-up time before training?', '0 minutes', '5-10 minutes', '30 minutes'),
('fitnesz_158', 'en', 'What type of exercise is running?', 'Anaerobic', 'Aerobic', 'Isometric'),
('fitnesz_159', 'en', 'Which muscle group does the deadlift primarily work?', 'Chest', 'Back and legs', 'Shoulders'),
('fitnesz_160', 'en', 'What is the function of a foam roller?', 'Building muscle', 'Muscle massage and recovery', 'Stretching'),
('fitnesz_161', 'en', 'How long should you stretch per muscle group?', '5 seconds', '15-30 seconds', '5 minutes'),
('fitnesz_162', 'en', 'What is compound exercise?', 'Single muscle exercise', 'Multi-muscle exercise', 'Stretching'),
('fitnesz_163', 'en', 'Which exercise best develops the shoulders?', 'Squats', 'Overhead press', 'Lunges'),
('fitnesz_164', 'en', 'What is the recommended weekly cardio duration?', '30 minutes', '150 minutes', '500 minutes'),
('fitnesz_165', 'en', 'What is muscle hypertrophy?', 'Muscle shrinkage', 'Muscle growth', 'Muscle stretching'),
('fitnesz_166', 'en', 'Which exercise develops the biceps?', 'Tricep dips', 'Bicep curls', 'Squats'),
('fitnesz_167', 'en', 'What is isometric training?', 'Movement with weight', 'Static muscle tension', 'Running'),
('fitnesz_168', 'en', 'How much sleep is recommended for muscle recovery?', '4-5 hours', '7-9 hours', '12 hours'),
('fitnesz_169', 'en', 'What is plyometric training?', 'Slow strength training', 'Explosive power exercises', 'Stretching'),
('fitnesz_170', 'en', 'Which exercise works the triceps?', 'Bicep curls', 'Tricep pushdowns', 'Squats'),
('fitnesz_171', 'en', 'What is training volume?', 'Only weight', 'Sets x reps x weight', 'Training time'),
('fitnesz_172', 'en', 'What does core training strengthen?', 'Arms', 'Core muscles', 'Legs'),
('fitnesz_173', 'en', 'What is circuit training?', 'Single exercise focus', 'Multiple exercises with minimal rest', 'Stretching only'),
('fitnesz_174', 'en', 'Which exercise develops the calves?', 'Bench press', 'Calf raises', 'Pull-ups'),
('fitnesz_175', 'en', 'What is eccentric movement?', 'Muscle shortening', 'Muscle lengthening under load', 'Rest'),
('fitnesz_176', 'en', 'How much protein is recommended per kg body weight for athletes?', '0.5g', '1.6-2.2g', '5g'),
('fitnesz_177', 'en', 'What is functional training?', 'Isolated muscle work', 'Everyday movement patterns', 'Cardio only'),
('fitnesz_178', 'en', 'Which exercise develops the lats?', 'Squats', 'Lat pulldown', 'Leg press'),
('fitnesz_179', 'en', 'What is training periodization?', 'Random workouts', 'Planned training cycles', 'Daily same workout'),
('fitnesz_180', 'en', 'What is a superset?', 'Long rest', 'Two exercises back-to-back', 'Single set'),
('fitnesz_181', 'en', 'Which exercise targets the hamstrings?', 'Leg curls', 'Bench press', 'Shoulder press'),
('fitnesz_182', 'en', 'What is the anaerobic threshold?', 'Low intensity point', 'High intensity point where lactate builds up', 'Rest point'),
('fitnesz_183', 'en', 'What is drop set?', 'Increasing weight', 'Decreasing weight without rest', 'Long rest'),
('fitnesz_184', 'en', 'What is the ideal rep range for muscle building?', '1-3 reps', '8-12 reps', '25-30 reps'),
('fitnesz_185', 'en', 'Which exercise develops the glutes?', 'Hip thrust', 'Bicep curl', 'Tricep dip'),
('fitnesz_186', 'en', 'What is muscle failure?', 'Injury', 'Unable to complete another rep', 'Rest'),
('fitnesz_187', 'en', 'What is the purpose of a deload week?', 'Maximum training', 'Recovery and reduced intensity', 'No training'),
('fitnesz_188', 'en', 'Which exercise develops the trapezius?', 'Squats', 'Shrugs', 'Lunges'),
('fitnesz_189', 'en', 'What is time under tension?', 'Rest time', 'Duration of muscle tension', 'Workout length'),
('fitnesz_190', 'en', 'What is unilateral training?', 'Both sides together', 'One side at a time', 'No equipment'),
('fitnesz_191', 'en', 'Which exercise works the forearms?', 'Wrist curls', 'Squats', 'Chest fly'),
('fitnesz_192', 'en', 'What is active recovery?', 'Complete rest', 'Light exercise on rest days', 'Maximum training'),
('fitnesz_193', 'en', 'What is the ideal rest between workouts for the same muscle?', '24 hours', '48-72 hours', '1 week'),
('fitnesz_194', 'en', 'What is concentric movement?', 'Muscle lengthening', 'Muscle shortening', 'Static hold'),
('fitnesz_195', 'en', 'Which exercise targets the obliques?', 'Russian twists', 'Bench press', 'Squats'),
('fitnesz_196', 'en', 'What is mind-muscle connection?', 'Not thinking', 'Focusing on the working muscle', 'Distraction'),
('fitnesz_197', 'en', 'What is the recommended warm-up heart rate?', '50% max', '60-70% max', '95% max'),
('fitnesz_198', 'en', 'What is resistance band training?', 'Cardio', 'Elastic band resistance exercises', 'Stretching'),
('fitnesz_199', 'en', 'Which muscle stabilizes the shoulder?', 'Biceps', 'Rotator cuff', 'Triceps'),
('fitnesz_200', 'en', 'What is bodyweight training?', 'Heavy weights', 'Using own body as resistance', 'Swimming')
ON CONFLICT (question_id, lang) DO NOTHING;
