
-- Topic 1: Egészség (Health) - 50 English translations (IDs 151-200)
INSERT INTO question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c) VALUES
('egeszseg_151', 'en', 'What is another name for HDL cholesterol?', 'Bad cholesterol', 'Good cholesterol', 'Fat cholesterol'),
('egeszseg_152', 'en', 'Which organ is responsible for producing digestive enzymes?', 'Liver', 'Stomach', 'Pancreas'),
('egeszseg_153', 'en', 'What is the main symptom of anemia?', 'High blood pressure', 'Fatigue and paleness', 'Fever'),
('egeszseg_154', 'en', 'Which hormone regulates calcium levels in the blood?', 'Insulin', 'Thyroid hormone', 'Parathyroid hormone'),
('egeszseg_155', 'en', 'What is glaucoma?', 'Clouding of the eye lens', 'Increased eye pressure', 'Eye allergy'),
('egeszseg_156', 'en', 'What is the recommended daily water intake for adults?', '0.5 liters', '1 liter', '2-2.5 liters'),
('egeszseg_157', 'en', 'What is the main characteristic of osteoporosis?', 'Joint inflammation', 'Decreased bone density', 'Muscle atrophy'),
('egeszseg_158', 'en', 'Which vitamin is needed for bone health besides calcium?', 'Vitamin A', 'Vitamin B', 'Vitamin C'),
('egeszseg_159', 'en', 'What is a migraine?', 'Mild headache', 'Throbbing, severe headache', 'Neck pain'),
('egeszseg_160', 'en', 'Which organ produces bile?', 'Pancreas', 'Liver', 'Gallbladder'),
('egeszseg_161', 'en', 'What is hypothermia?', 'High body temperature', 'Low body temperature', 'Normal body temperature'),
('egeszseg_162', 'en', 'Which disease involves blood sugar metabolism disorder?', 'Asthma', 'Diabetes', 'High blood pressure'),
('egeszseg_163', 'en', 'What is endoscopy?', 'X-ray examination', 'Internal organ camera examination', 'Blood test'),
('egeszseg_164', 'en', 'How many bones are in the adult human body?', '150', '206', '256'),
('egeszseg_165', 'en', 'What is the main cause of pneumonia?', 'Virus or bacteria', 'Allergy', 'Smoking'),
('egeszseg_166', 'en', 'Which hormone is responsible for the female menstrual cycle?', 'Testosterone', 'Estrogen and progesterone', 'Insulin'),
('egeszseg_167', 'en', 'What is the most common allergic reaction?', 'Fainting', 'Sneezing and itching', 'Fever'),
('egeszseg_168', 'en', 'Which system is responsible for defending against diseases?', 'Respiratory system', 'Digestive system', 'Immune system'),
('egeszseg_169', 'en', 'What is hypertension?', 'Low blood pressure', 'High blood pressure', 'Normal blood pressure'),
('egeszseg_170', 'en', 'Which organ filters waste from the blood?', 'Heart', 'Liver', 'Kidney'),
('egeszseg_171', 'en', 'What is the main function of red blood cells?', 'Fighting infections', 'Transporting oxygen', 'Blood clotting'),
('egeszseg_172', 'en', 'Which vitamin is important for blood clotting?', 'Vitamin A', 'Vitamin C', 'Vitamin K'),
('egeszseg_173', 'en', 'What is tinnitus?', 'Hearing loss', 'Ringing in the ears', 'Ear pain'),
('egeszseg_174', 'en', 'Which organ is the largest in the human body?', 'Liver', 'Brain', 'Skin'),
('egeszseg_175', 'en', 'What is the main symptom of asthma?', 'Skin rash', 'Difficulty breathing', 'Fever'),
('egeszseg_176', 'en', 'Which gland produces insulin?', 'Thyroid', 'Adrenal gland', 'Pancreas'),
('egeszseg_177', 'en', 'What is a stroke?', 'Heart attack', 'Brain blood supply disruption', 'Lung disease'),
('egeszseg_178', 'en', 'Which mineral is important for muscle function?', 'Iron', 'Calcium', 'Magnesium'),
('egeszseg_179', 'en', 'What is the normal resting heart rate?', '40-50 beats/min', '60-100 beats/min', '120-140 beats/min'),
('egeszseg_180', 'en', 'Which vitamin deficiency causes scurvy?', 'Vitamin A', 'Vitamin B', 'Vitamin C'),
('egeszseg_181', 'en', 'What is the main function of platelets?', 'Transporting oxygen', 'Fighting infections', 'Blood clotting'),
('egeszseg_182', 'en', 'Which organ produces hormones that regulate metabolism?', 'Liver', 'Thyroid', 'Kidney'),
('egeszseg_183', 'en', 'What is heartburn?', 'Heart disease', 'Stomach acid reflux', 'Lung problem'),
('egeszseg_184', 'en', 'How many chambers does the human heart have?', '2', '3', '4'),
('egeszseg_185', 'en', 'What is the main cause of type 2 diabetes?', 'Virus infection', 'Obesity and lifestyle', 'Genetics only'),
('egeszseg_186', 'en', 'Which vitamin is produced by sunlight exposure?', 'Vitamin A', 'Vitamin B12', 'Vitamin D'),
('egeszseg_187', 'en', 'What is appendicitis?', 'Liver inflammation', 'Appendix inflammation', 'Stomach inflammation'),
('egeszseg_188', 'en', 'Which blood type is the universal donor?', 'A', 'B', 'O'),
('egeszseg_189', 'en', 'What is the main function of the lymphatic system?', 'Digestion', 'Immune defense', 'Blood circulation'),
('egeszseg_190', 'en', 'What causes kidney stones?', 'Bacteria', 'Mineral deposits', 'Virus'),
('egeszseg_191', 'en', 'Which part of the brain controls balance?', 'Frontal lobe', 'Cerebellum', 'Brain stem'),
('egeszseg_192', 'en', 'What is the normal blood pressure range?', '80/50 mmHg', '120/80 mmHg', '160/100 mmHg'),
('egeszseg_193', 'en', 'What causes jaundice?', 'Low iron', 'Excess bilirubin', 'Vitamin deficiency'),
('egeszseg_194', 'en', 'How long does a complete blood circulation take?', '10 seconds', '20 seconds', '60 seconds'),
('egeszseg_195', 'en', 'What is arthritis?', 'Bone disease', 'Joint inflammation', 'Muscle disease'),
('egeszseg_196', 'en', 'Which organ stores glycogen?', 'Heart', 'Liver', 'Kidney'),
('egeszseg_197', 'en', 'What is the main symptom of dehydration?', 'Fever', 'Thirst and dry mouth', 'Coughing'),
('egeszseg_198', 'en', 'Which system is responsible for hormone production?', 'Nervous system', 'Endocrine system', 'Digestive system'),
('egeszseg_199', 'en', 'What is the function of melatonin?', 'Digestion', 'Sleep regulation', 'Muscle growth'),
('egeszseg_200', 'en', 'What is an electrocardiogram (ECG)?', 'Brain scan', 'Heart electrical activity test', 'Lung function test')
ON CONFLICT (question_id, lang) DO NOTHING;
