-- Topic 9 (Technológia) - 50 új kérdés (tech_151 - tech_200)
INSERT INTO questions (id, question, answers, correct_answer, topic_id, audience, third, source_category) VALUES
('tech_151', 'Melyik cég gyártja az iPhone-t?', '[{"key":"A","text":"Samsung","correct":false},{"key":"B","text":"Apple","correct":true},{"key":"C","text":"Google","correct":false}]', 'B', 9, '{"A":5,"B":90,"C":5}', 'B', 'mixed'),
('tech_152', 'Mi a HTML rövidítés jelentése?', '[{"key":"A","text":"High Tech Markup Language","correct":false},{"key":"B","text":"HyperText Markup Language","correct":true},{"key":"C","text":"Home Tool Markup Language","correct":false}]', 'B', 9, '{"A":20,"B":65,"C":15}', 'B', 'mixed'),
('tech_153', 'Melyik évben indult a Facebook?', '[{"key":"A","text":"2002","correct":false},{"key":"B","text":"2004","correct":true},{"key":"C","text":"2006","correct":false}]', 'B', 9, '{"A":20,"B":60,"C":20}', 'B', 'mixed'),
('tech_154', 'Ki alapította a Microsoft-ot?', '[{"key":"A","text":"Steve Jobs","correct":false},{"key":"B","text":"Bill Gates","correct":true},{"key":"C","text":"Mark Zuckerberg","correct":false}]', 'B', 9, '{"A":10,"B":85,"C":5}', 'B', 'mixed'),
('tech_155', 'Mi a CPU rövidítés jelentése?', '[{"key":"A","text":"Computer Personal Unit","correct":false},{"key":"B","text":"Central Processing Unit","correct":true},{"key":"C","text":"Central Power Unit","correct":false}]', 'B', 9, '{"A":15,"B":75,"C":10}', 'B', 'mixed'),
('tech_156', 'Melyik operációs rendszert fejlesztette a Google mobiltelefonokra?', '[{"key":"A","text":"iOS","correct":false},{"key":"B","text":"Android","correct":true},{"key":"C","text":"Windows Phone","correct":false}]', 'B', 9, '{"A":10,"B":85,"C":5}', 'B', 'mixed'),
('tech_157', 'Mi a neve a legnagyobb online könyvesboltnak?', '[{"key":"A","text":"eBay","correct":false},{"key":"B","text":"Amazon","correct":true},{"key":"C","text":"Alibaba","correct":false}]', 'B', 9, '{"A":10,"B":80,"C":10}', 'B', 'mixed'),
('tech_158', 'Hány bit van egy byte-ban?', '[{"key":"A","text":"4","correct":false},{"key":"B","text":"8","correct":true},{"key":"C","text":"16","correct":false}]', 'B', 9, '{"A":20,"B":65,"C":15}', 'B', 'mixed'),
('tech_159', 'Melyik cég gyártja a PlayStation konzolt?', '[{"key":"A","text":"Microsoft","correct":false},{"key":"B","text":"Sony","correct":true},{"key":"C","text":"Nintendo","correct":false}]', 'B', 9, '{"A":10,"B":80,"C":10}', 'B', 'mixed'),
('tech_160', 'Mi a neve a Google keresőmotorjának?', '[{"key":"A","text":"Bing","correct":false},{"key":"B","text":"Google Search","correct":true},{"key":"C","text":"Yahoo","correct":false}]', 'B', 9, '{"A":10,"B":80,"C":10}', 'B', 'mixed'),
('tech_161', 'Melyik évben indult a YouTube?', '[{"key":"A","text":"2003","correct":false},{"key":"B","text":"2005","correct":true},{"key":"C","text":"2007","correct":false}]', 'B', 9, '{"A":25,"B":55,"C":20}', 'B', 'mixed'),
('tech_162', 'Mi a WiFi jelentése?', '[{"key":"A","text":"Wired Fidelity","correct":false},{"key":"B","text":"Wireless Fidelity","correct":true},{"key":"C","text":"Wide Frequency","correct":false}]', 'B', 9, '{"A":20,"B":65,"C":15}', 'B', 'mixed'),
('tech_163', 'Melyik cég gyártja a Galaxy okostelefonokat?', '[{"key":"A","text":"LG","correct":false},{"key":"B","text":"Samsung","correct":true},{"key":"C","text":"Huawei","correct":false}]', 'B', 9, '{"A":10,"B":80,"C":10}', 'B', 'mixed'),
('tech_164', 'Mi a RAM rövidítés jelentése?', '[{"key":"A","text":"Read Access Memory","correct":false},{"key":"B","text":"Random Access Memory","correct":true},{"key":"C","text":"Rapid Access Memory","correct":false}]', 'B', 9, '{"A":20,"B":65,"C":15}', 'B', 'mixed'),
('tech_165', 'Melyik programnyelvet használják leggyakrabban webfejlesztéshez?', '[{"key":"A","text":"Python","correct":false},{"key":"B","text":"JavaScript","correct":true},{"key":"C","text":"C++","correct":false}]', 'B', 9, '{"A":25,"B":60,"C":15}', 'B', 'mixed'),
('tech_166', 'Ki alapította az Amazon-t?', '[{"key":"A","text":"Elon Musk","correct":false},{"key":"B","text":"Jeff Bezos","correct":true},{"key":"C","text":"Larry Page","correct":false}]', 'B', 9, '{"A":15,"B":75,"C":10}', 'B', 'mixed'),
('tech_167', 'Mi a neve a legnépszerűbb videójáték streaming platformnak?', '[{"key":"A","text":"YouTube Gaming","correct":false},{"key":"B","text":"Twitch","correct":true},{"key":"C","text":"Mixer","correct":false}]', 'B', 9, '{"A":25,"B":65,"C":10}', 'B', 'mixed'),
('tech_168', 'Melyik cég fejlesztette a ChatGPT-t?', '[{"key":"A","text":"Google","correct":false},{"key":"B","text":"OpenAI","correct":true},{"key":"C","text":"Microsoft","correct":false}]', 'B', 9, '{"A":20,"B":70,"C":10}', 'B', 'mixed'),
('tech_169', 'Mi a URL rövidítés jelentése?', '[{"key":"A","text":"Universal Resource Link","correct":false},{"key":"B","text":"Uniform Resource Locator","correct":true},{"key":"C","text":"United Resource Location","correct":false}]', 'B', 9, '{"A":25,"B":55,"C":20}', 'B', 'mixed'),
('tech_170', 'Melyik évben jelent meg az első iPhone?', '[{"key":"A","text":"2005","correct":false},{"key":"B","text":"2007","correct":true},{"key":"C","text":"2009","correct":false}]', 'B', 9, '{"A":20,"B":65,"C":15}', 'B', 'mixed'),
('tech_171', 'Mi a neve az Apple asztali operációs rendszerének?', '[{"key":"A","text":"iOS","correct":false},{"key":"B","text":"macOS","correct":true},{"key":"C","text":"watchOS","correct":false}]', 'B', 9, '{"A":20,"B":70,"C":10}', 'B', 'mixed'),
('tech_172', 'Melyik cég gyártja az Xbox konzolt?', '[{"key":"A","text":"Sony","correct":false},{"key":"B","text":"Microsoft","correct":true},{"key":"C","text":"Nintendo","correct":false}]', 'B', 9, '{"A":15,"B":75,"C":10}', 'B', 'mixed'),
('tech_173', 'Mi a PDF rövidítés jelentése?', '[{"key":"A","text":"Personal Document File","correct":false},{"key":"B","text":"Portable Document Format","correct":true},{"key":"C","text":"Printed Document Format","correct":false}]', 'B', 9, '{"A":20,"B":65,"C":15}', 'B', 'mixed'),
('tech_174', 'Melyik a világ legnagyobb közösségi média platformja?', '[{"key":"A","text":"Twitter","correct":false},{"key":"B","text":"Facebook","correct":true},{"key":"C","text":"Instagram","correct":false}]', 'B', 9, '{"A":15,"B":70,"C":15}', 'B', 'mixed'),
('tech_175', 'Ki alapította a Tesla-t?', '[{"key":"A","text":"Jeff Bezos","correct":false},{"key":"B","text":"Elon Musk","correct":true},{"key":"C","text":"Bill Gates","correct":false}]', 'B', 9, '{"A":10,"B":80,"C":10}', 'B', 'mixed'),
('tech_176', 'Mi a GPS rövidítés jelentése?', '[{"key":"A","text":"General Positioning Service","correct":false},{"key":"B","text":"Global Positioning System","correct":true},{"key":"C","text":"Geographic Position Satellite","correct":false}]', 'B', 9, '{"A":20,"B":65,"C":15}', 'B', 'mixed'),
('tech_177', 'Melyik programnyelvet fejlesztette a Sun Microsystems?', '[{"key":"A","text":"Python","correct":false},{"key":"B","text":"Java","correct":true},{"key":"C","text":"C#","correct":false}]', 'B', 9, '{"A":25,"B":55,"C":20}', 'B', 'mixed'),
('tech_178', 'Mi a neve az Apple okosórájának?', '[{"key":"A","text":"iWatch","correct":false},{"key":"B","text":"Apple Watch","correct":true},{"key":"C","text":"Apple Time","correct":false}]', 'B', 9, '{"A":25,"B":65,"C":10}', 'B', 'mixed'),
('tech_179', 'Melyik cég gyártja a Pixel telefonokat?', '[{"key":"A","text":"Samsung","correct":false},{"key":"B","text":"Google","correct":true},{"key":"C","text":"OnePlus","correct":false}]', 'B', 9, '{"A":20,"B":65,"C":15}', 'B', 'mixed'),
('tech_180', 'Mi a SSD rövidítés jelentése?', '[{"key":"A","text":"Super Speed Drive","correct":false},{"key":"B","text":"Solid State Drive","correct":true},{"key":"C","text":"System Storage Device","correct":false}]', 'B', 9, '{"A":25,"B":55,"C":20}', 'B', 'mixed'),
('tech_181', 'Melyik évben alapították a Google-t?', '[{"key":"A","text":"1996","correct":false},{"key":"B","text":"1998","correct":true},{"key":"C","text":"2000","correct":false}]', 'B', 9, '{"A":25,"B":55,"C":20}', 'B', 'mixed'),
('tech_182', 'Mi a neve a Microsoft irodai programcsomagjának?', '[{"key":"A","text":"Microsoft Suite","correct":false},{"key":"B","text":"Microsoft Office","correct":true},{"key":"C","text":"Microsoft Work","correct":false}]', 'B', 9, '{"A":10,"B":85,"C":5}', 'B', 'mixed'),
('tech_183', 'Melyik cég gyártja a Switch játékkonzolt?', '[{"key":"A","text":"Sony","correct":false},{"key":"B","text":"Nintendo","correct":true},{"key":"C","text":"Microsoft","correct":false}]', 'B', 9, '{"A":15,"B":75,"C":10}', 'B', 'mixed'),
('tech_184', 'Mi az AI rövidítés jelentése?', '[{"key":"A","text":"Automated Intelligence","correct":false},{"key":"B","text":"Artificial Intelligence","correct":true},{"key":"C","text":"Advanced Integration","correct":false}]', 'B', 9, '{"A":20,"B":70,"C":10}', 'B', 'mixed'),
('tech_185', 'Melyik a legnépszerűbb videómegosztó platform?', '[{"key":"A","text":"Vimeo","correct":false},{"key":"B","text":"YouTube","correct":true},{"key":"C","text":"Dailymotion","correct":false}]', 'B', 9, '{"A":5,"B":90,"C":5}', 'B', 'mixed'),
('tech_186', 'Ki alapította a SpaceX-et?', '[{"key":"A","text":"Jeff Bezos","correct":false},{"key":"B","text":"Elon Musk","correct":true},{"key":"C","text":"Richard Branson","correct":false}]', 'B', 9, '{"A":15,"B":75,"C":10}', 'B', 'mixed'),
('tech_187', 'Mi a VPN rövidítés jelentése?', '[{"key":"A","text":"Virtual Personal Network","correct":false},{"key":"B","text":"Virtual Private Network","correct":true},{"key":"C","text":"Verified Private Network","correct":false}]', 'B', 9, '{"A":25,"B":60,"C":15}', 'B', 'mixed'),
('tech_188', 'Melyik cég fejlesztette a Windows operációs rendszert?', '[{"key":"A","text":"Apple","correct":false},{"key":"B","text":"Microsoft","correct":true},{"key":"C","text":"IBM","correct":false}]', 'B', 9, '{"A":5,"B":90,"C":5}', 'B', 'mixed'),
('tech_189', 'Mi a neve a Google e-mail szolgáltatásának?', '[{"key":"A","text":"Google Mail","correct":false},{"key":"B","text":"Gmail","correct":true},{"key":"C","text":"G-Post","correct":false}]', 'B', 9, '{"A":15,"B":80,"C":5}', 'B', 'mixed'),
('tech_190', 'Melyik évben indult a Twitter?', '[{"key":"A","text":"2004","correct":false},{"key":"B","text":"2006","correct":true},{"key":"C","text":"2008","correct":false}]', 'B', 9, '{"A":25,"B":55,"C":20}', 'B', 'mixed'),
('tech_191', 'Mi a LED rövidítés jelentése?', '[{"key":"A","text":"Light Electric Device","correct":false},{"key":"B","text":"Light Emitting Diode","correct":true},{"key":"C","text":"Low Energy Display","correct":false}]', 'B', 9, '{"A":20,"B":60,"C":20}', 'B', 'mixed'),
('tech_192', 'Melyik cég gyártja a Kindle e-könyv olvasót?', '[{"key":"A","text":"Apple","correct":false},{"key":"B","text":"Amazon","correct":true},{"key":"C","text":"Sony","correct":false}]', 'B', 9, '{"A":15,"B":70,"C":15}', 'B', 'mixed'),
('tech_193', 'Mi a neve a legismertebb nyílt forráskódú operációs rendszernek?', '[{"key":"A","text":"Unix","correct":false},{"key":"B","text":"Linux","correct":true},{"key":"C","text":"FreeBSD","correct":false}]', 'B', 9, '{"A":25,"B":60,"C":15}', 'B', 'mixed'),
('tech_194', 'Melyik cég fejlesztette a Chrome böngészőt?', '[{"key":"A","text":"Mozilla","correct":false},{"key":"B","text":"Google","correct":true},{"key":"C","text":"Microsoft","correct":false}]', 'B', 9, '{"A":20,"B":70,"C":10}', 'B', 'mixed'),
('tech_195', 'Mi az USB rövidítés jelentése?', '[{"key":"A","text":"Universal System Bus","correct":false},{"key":"B","text":"Universal Serial Bus","correct":true},{"key":"C","text":"United Serial Bus","correct":false}]', 'B', 9, '{"A":25,"B":55,"C":20}', 'B', 'mixed'),
('tech_196', 'Melyik a világ legnagyobb chipgyártója?', '[{"key":"A","text":"AMD","correct":false},{"key":"B","text":"TSMC","correct":true},{"key":"C","text":"Intel","correct":false}]', 'B', 9, '{"A":25,"B":45,"C":30}', 'B', 'mixed'),
('tech_197', 'Mi a neve az Apple vezeték nélküli fülhallgatójának?', '[{"key":"A","text":"Apple Buds","correct":false},{"key":"B","text":"AirPods","correct":true},{"key":"C","text":"iBuds","correct":false}]', 'B', 9, '{"A":15,"B":75,"C":10}', 'B', 'mixed'),
('tech_198', 'Melyik cég gyártja a GeForce videokártyákat?', '[{"key":"A","text":"AMD","correct":false},{"key":"B","text":"NVIDIA","correct":true},{"key":"C","text":"Intel","correct":false}]', 'B', 9, '{"A":25,"B":60,"C":15}', 'B', 'mixed'),
('tech_199', 'Mi a QR-kód jelentése?', '[{"key":"A","text":"Quick Read","correct":false},{"key":"B","text":"Quick Response","correct":true},{"key":"C","text":"Query Response","correct":false}]', 'B', 9, '{"A":30,"B":50,"C":20}', 'B', 'mixed'),
('tech_200', 'Melyik évben indult az Instagram?', '[{"key":"A","text":"2008","correct":false},{"key":"B","text":"2010","correct":true},{"key":"C","text":"2012","correct":false}]', 'B', 9, '{"A":25,"B":55,"C":20}', 'B', 'mixed');

-- Topic 9 fordítások (tech_151 - tech_200)
INSERT INTO question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c) VALUES
('tech_151', 'hu', 'Melyik cég gyártja az iPhone-t?', 'Samsung', 'Apple', 'Google'),
('tech_151', 'en', 'Which company manufactures the iPhone?', 'Samsung', 'Apple', 'Google'),
('tech_152', 'hu', 'Mi a HTML rövidítés jelentése?', 'High Tech Markup Language', 'HyperText Markup Language', 'Home Tool Markup Language'),
('tech_152', 'en', 'What does HTML stand for?', 'High Tech Markup Language', 'HyperText Markup Language', 'Home Tool Markup Language'),
('tech_153', 'hu', 'Melyik évben indult a Facebook?', '2002', '2004', '2006'),
('tech_153', 'en', 'In which year was Facebook launched?', '2002', '2004', '2006'),
('tech_154', 'hu', 'Ki alapította a Microsoft-ot?', 'Steve Jobs', 'Bill Gates', 'Mark Zuckerberg'),
('tech_154', 'en', 'Who founded Microsoft?', 'Steve Jobs', 'Bill Gates', 'Mark Zuckerberg'),
('tech_155', 'hu', 'Mi a CPU rövidítés jelentése?', 'Computer Personal Unit', 'Central Processing Unit', 'Central Power Unit'),
('tech_155', 'en', 'What does CPU stand for?', 'Computer Personal Unit', 'Central Processing Unit', 'Central Power Unit'),
('tech_156', 'hu', 'Melyik operációs rendszert fejlesztette a Google mobiltelefonokra?', 'iOS', 'Android', 'Windows Phone'),
('tech_156', 'en', 'Which operating system did Google develop for mobile phones?', 'iOS', 'Android', 'Windows Phone'),
('tech_157', 'hu', 'Mi a neve a legnagyobb online könyvesboltnak?', 'eBay', 'Amazon', 'Alibaba'),
('tech_157', 'en', 'What is the name of the largest online bookstore?', 'eBay', 'Amazon', 'Alibaba'),
('tech_158', 'hu', 'Hány bit van egy byte-ban?', '4', '8', '16'),
('tech_158', 'en', 'How many bits are in a byte?', '4', '8', '16'),
('tech_159', 'hu', 'Melyik cég gyártja a PlayStation konzolt?', 'Microsoft', 'Sony', 'Nintendo'),
('tech_159', 'en', 'Which company manufactures the PlayStation console?', 'Microsoft', 'Sony', 'Nintendo'),
('tech_160', 'hu', 'Mi a neve a Google keresőmotorjának?', 'Bing', 'Google Search', 'Yahoo'),
('tech_160', 'en', 'What is the name of Google search engine?', 'Bing', 'Google Search', 'Yahoo'),
('tech_161', 'hu', 'Melyik évben indult a YouTube?', '2003', '2005', '2007'),
('tech_161', 'en', 'In which year was YouTube launched?', '2003', '2005', '2007'),
('tech_162', 'hu', 'Mi a WiFi jelentése?', 'Wired Fidelity', 'Wireless Fidelity', 'Wide Frequency'),
('tech_162', 'en', 'What does WiFi stand for?', 'Wired Fidelity', 'Wireless Fidelity', 'Wide Frequency'),
('tech_163', 'hu', 'Melyik cég gyártja a Galaxy okostelefonokat?', 'LG', 'Samsung', 'Huawei'),
('tech_163', 'en', 'Which company manufactures Galaxy smartphones?', 'LG', 'Samsung', 'Huawei'),
('tech_164', 'hu', 'Mi a RAM rövidítés jelentése?', 'Read Access Memory', 'Random Access Memory', 'Rapid Access Memory'),
('tech_164', 'en', 'What does RAM stand for?', 'Read Access Memory', 'Random Access Memory', 'Rapid Access Memory'),
('tech_165', 'hu', 'Melyik programnyelvet használják leggyakrabban webfejlesztéshez?', 'Python', 'JavaScript', 'C++'),
('tech_165', 'en', 'Which programming language is most commonly used for web development?', 'Python', 'JavaScript', 'C++'),
('tech_166', 'hu', 'Ki alapította az Amazon-t?', 'Elon Musk', 'Jeff Bezos', 'Larry Page'),
('tech_166', 'en', 'Who founded Amazon?', 'Elon Musk', 'Jeff Bezos', 'Larry Page'),
('tech_167', 'hu', 'Mi a neve a legnépszerűbb videójáték streaming platformnak?', 'YouTube Gaming', 'Twitch', 'Mixer'),
('tech_167', 'en', 'What is the name of the most popular video game streaming platform?', 'YouTube Gaming', 'Twitch', 'Mixer'),
('tech_168', 'hu', 'Melyik cég fejlesztette a ChatGPT-t?', 'Google', 'OpenAI', 'Microsoft'),
('tech_168', 'en', 'Which company developed ChatGPT?', 'Google', 'OpenAI', 'Microsoft'),
('tech_169', 'hu', 'Mi a URL rövidítés jelentése?', 'Universal Resource Link', 'Uniform Resource Locator', 'United Resource Location'),
('tech_169', 'en', 'What does URL stand for?', 'Universal Resource Link', 'Uniform Resource Locator', 'United Resource Location'),
('tech_170', 'hu', 'Melyik évben jelent meg az első iPhone?', '2005', '2007', '2009'),
('tech_170', 'en', 'In which year was the first iPhone released?', '2005', '2007', '2009'),
('tech_171', 'hu', 'Mi a neve az Apple asztali operációs rendszerének?', 'iOS', 'macOS', 'watchOS'),
('tech_171', 'en', 'What is the name of Apple desktop operating system?', 'iOS', 'macOS', 'watchOS'),
('tech_172', 'hu', 'Melyik cég gyártja az Xbox konzolt?', 'Sony', 'Microsoft', 'Nintendo'),
('tech_172', 'en', 'Which company manufactures the Xbox console?', 'Sony', 'Microsoft', 'Nintendo'),
('tech_173', 'hu', 'Mi a PDF rövidítés jelentése?', 'Personal Document File', 'Portable Document Format', 'Printed Document Format'),
('tech_173', 'en', 'What does PDF stand for?', 'Personal Document File', 'Portable Document Format', 'Printed Document Format'),
('tech_174', 'hu', 'Melyik a világ legnagyobb közösségi média platformja?', 'Twitter', 'Facebook', 'Instagram'),
('tech_174', 'en', 'Which is the world largest social media platform?', 'Twitter', 'Facebook', 'Instagram'),
('tech_175', 'hu', 'Ki alapította a Tesla-t?', 'Jeff Bezos', 'Elon Musk', 'Bill Gates'),
('tech_175', 'en', 'Who founded Tesla?', 'Jeff Bezos', 'Elon Musk', 'Bill Gates'),
('tech_176', 'hu', 'Mi a GPS rövidítés jelentése?', 'General Positioning Service', 'Global Positioning System', 'Geographic Position Satellite'),
('tech_176', 'en', 'What does GPS stand for?', 'General Positioning Service', 'Global Positioning System', 'Geographic Position Satellite'),
('tech_177', 'hu', 'Melyik programnyelvet fejlesztette a Sun Microsystems?', 'Python', 'Java', 'C#'),
('tech_177', 'en', 'Which programming language was developed by Sun Microsystems?', 'Python', 'Java', 'C#'),
('tech_178', 'hu', 'Mi a neve az Apple okosórájának?', 'iWatch', 'Apple Watch', 'Apple Time'),
('tech_178', 'en', 'What is the name of Apple smartwatch?', 'iWatch', 'Apple Watch', 'Apple Time'),
('tech_179', 'hu', 'Melyik cég gyártja a Pixel telefonokat?', 'Samsung', 'Google', 'OnePlus'),
('tech_179', 'en', 'Which company manufactures Pixel phones?', 'Samsung', 'Google', 'OnePlus'),
('tech_180', 'hu', 'Mi a SSD rövidítés jelentése?', 'Super Speed Drive', 'Solid State Drive', 'System Storage Device'),
('tech_180', 'en', 'What does SSD stand for?', 'Super Speed Drive', 'Solid State Drive', 'System Storage Device'),
('tech_181', 'hu', 'Melyik évben alapították a Google-t?', '1996', '1998', '2000'),
('tech_181', 'en', 'In which year was Google founded?', '1996', '1998', '2000'),
('tech_182', 'hu', 'Mi a neve a Microsoft irodai programcsomagjának?', 'Microsoft Suite', 'Microsoft Office', 'Microsoft Work'),
('tech_182', 'en', 'What is the name of Microsoft office suite?', 'Microsoft Suite', 'Microsoft Office', 'Microsoft Work'),
('tech_183', 'hu', 'Melyik cég gyártja a Switch játékkonzolt?', 'Sony', 'Nintendo', 'Microsoft'),
('tech_183', 'en', 'Which company manufactures the Switch game console?', 'Sony', 'Nintendo', 'Microsoft'),
('tech_184', 'hu', 'Mi az AI rövidítés jelentése?', 'Automated Intelligence', 'Artificial Intelligence', 'Advanced Integration'),
('tech_184', 'en', 'What does AI stand for?', 'Automated Intelligence', 'Artificial Intelligence', 'Advanced Integration'),
('tech_185', 'hu', 'Melyik a legnépszerűbb videómegosztó platform?', 'Vimeo', 'YouTube', 'Dailymotion'),
('tech_185', 'en', 'Which is the most popular video sharing platform?', 'Vimeo', 'YouTube', 'Dailymotion'),
('tech_186', 'hu', 'Ki alapította a SpaceX-et?', 'Jeff Bezos', 'Elon Musk', 'Richard Branson'),
('tech_186', 'en', 'Who founded SpaceX?', 'Jeff Bezos', 'Elon Musk', 'Richard Branson'),
('tech_187', 'hu', 'Mi a VPN rövidítés jelentése?', 'Virtual Personal Network', 'Virtual Private Network', 'Verified Private Network'),
('tech_187', 'en', 'What does VPN stand for?', 'Virtual Personal Network', 'Virtual Private Network', 'Verified Private Network'),
('tech_188', 'hu', 'Melyik cég fejlesztette a Windows operációs rendszert?', 'Apple', 'Microsoft', 'IBM'),
('tech_188', 'en', 'Which company developed the Windows operating system?', 'Apple', 'Microsoft', 'IBM'),
('tech_189', 'hu', 'Mi a neve a Google e-mail szolgáltatásának?', 'Google Mail', 'Gmail', 'G-Post'),
('tech_189', 'en', 'What is the name of Google email service?', 'Google Mail', 'Gmail', 'G-Post'),
('tech_190', 'hu', 'Melyik évben indult a Twitter?', '2004', '2006', '2008'),
('tech_190', 'en', 'In which year was Twitter launched?', '2004', '2006', '2008'),
('tech_191', 'hu', 'Mi a LED rövidítés jelentése?', 'Light Electric Device', 'Light Emitting Diode', 'Low Energy Display'),
('tech_191', 'en', 'What does LED stand for?', 'Light Electric Device', 'Light Emitting Diode', 'Low Energy Display'),
('tech_192', 'hu', 'Melyik cég gyártja a Kindle e-könyv olvasót?', 'Apple', 'Amazon', 'Sony'),
('tech_192', 'en', 'Which company manufactures the Kindle e-reader?', 'Apple', 'Amazon', 'Sony'),
('tech_193', 'hu', 'Mi a neve a legismertebb nyílt forráskódú operációs rendszernek?', 'Unix', 'Linux', 'FreeBSD'),
('tech_193', 'en', 'What is the name of the most famous open source operating system?', 'Unix', 'Linux', 'FreeBSD'),
('tech_194', 'hu', 'Melyik cég fejlesztette a Chrome böngészőt?', 'Mozilla', 'Google', 'Microsoft'),
('tech_194', 'en', 'Which company developed the Chrome browser?', 'Mozilla', 'Google', 'Microsoft'),
('tech_195', 'hu', 'Mi az USB rövidítés jelentése?', 'Universal System Bus', 'Universal Serial Bus', 'United Serial Bus'),
('tech_195', 'en', 'What does USB stand for?', 'Universal System Bus', 'Universal Serial Bus', 'United Serial Bus'),
('tech_196', 'hu', 'Melyik a világ legnagyobb chipgyártója?', 'AMD', 'TSMC', 'Intel'),
('tech_196', 'en', 'Which is the world largest chip manufacturer?', 'AMD', 'TSMC', 'Intel'),
('tech_197', 'hu', 'Mi a neve az Apple vezeték nélküli fülhallgatójának?', 'Apple Buds', 'AirPods', 'iBuds'),
('tech_197', 'en', 'What is the name of Apple wireless earbuds?', 'Apple Buds', 'AirPods', 'iBuds'),
('tech_198', 'hu', 'Melyik cég gyártja a GeForce videokártyákat?', 'AMD', 'NVIDIA', 'Intel'),
('tech_198', 'en', 'Which company manufactures GeForce graphics cards?', 'AMD', 'NVIDIA', 'Intel'),
('tech_199', 'hu', 'Mi a QR-kód jelentése?', 'Quick Read', 'Quick Response', 'Query Response'),
('tech_199', 'en', 'What does QR code stand for?', 'Quick Read', 'Quick Response', 'Query Response'),
('tech_200', 'hu', 'Melyik évben indult az Instagram?', '2008', '2010', '2012'),
('tech_200', 'en', 'In which year was Instagram launched?', '2008', '2010', '2012')
ON CONFLICT (question_id, lang) DO NOTHING;