-- Topic 10 (Tudomány) - 50 új kérdés (science_151 - science_200)
INSERT INTO questions (id, question, answers, correct_answer, topic_id, audience, third, source_category) VALUES
('science_151', 'Mi a vegyjele a víznek?', '[{"key":"A","text":"CO2","correct":false},{"key":"B","text":"H2O","correct":true},{"key":"C","text":"O2","correct":false}]', 'B', 10, '{"A":10,"B":85,"C":5}', 'B', 'mixed'),
('science_152', 'Hány bolygó van a Naprendszerben?', '[{"key":"A","text":"7","correct":false},{"key":"B","text":"8","correct":true},{"key":"C","text":"9","correct":false}]', 'B', 10, '{"A":15,"B":75,"C":10}', 'B', 'mixed'),
('science_153', 'Mi a fény sebessége vákuumban?', '[{"key":"A","text":"200 000 km/s","correct":false},{"key":"B","text":"300 000 km/s","correct":true},{"key":"C","text":"400 000 km/s","correct":false}]', 'B', 10, '{"A":20,"B":65,"C":15}', 'B', 'mixed'),
('science_154', 'Mi az emberi test legkisebb csontja?', '[{"key":"A","text":"Kalapács","correct":false},{"key":"B","text":"Kengyel","correct":true},{"key":"C","text":"Üllő","correct":false}]', 'B', 10, '{"A":30,"B":45,"C":25}', 'B', 'mixed'),
('science_155', 'Mi a DNA rövidítés jelentése?', '[{"key":"A","text":"Dinukleotid Acid","correct":false},{"key":"B","text":"Dezoxiribonukleinsav","correct":true},{"key":"C","text":"Dinukleáris Anyag","correct":false}]', 'B', 10, '{"A":20,"B":60,"C":20}', 'B', 'mixed'),
('science_156', 'Melyik a legnagyobb bolygó a Naprendszerben?', '[{"key":"A","text":"Szaturnusz","correct":false},{"key":"B","text":"Jupiter","correct":true},{"key":"C","text":"Neptunusz","correct":false}]', 'B', 10, '{"A":20,"B":70,"C":10}', 'B', 'mixed'),
('science_157', 'Mi a vegyjele az aranynak?', '[{"key":"A","text":"Ag","correct":false},{"key":"B","text":"Au","correct":true},{"key":"C","text":"Ar","correct":false}]', 'B', 10, '{"A":25,"B":55,"C":20}', 'B', 'mixed'),
('science_158', 'Hány csont van a felnőtt emberi testben?', '[{"key":"A","text":"186","correct":false},{"key":"B","text":"206","correct":true},{"key":"C","text":"226","correct":false}]', 'B', 10, '{"A":25,"B":55,"C":20}', 'B', 'mixed'),
('science_159', 'Mi a Föld legbelső rétege?', '[{"key":"A","text":"Köpeny","correct":false},{"key":"B","text":"Mag","correct":true},{"key":"C","text":"Kéreg","correct":false}]', 'B', 10, '{"A":20,"B":65,"C":15}', 'B', 'mixed'),
('science_160', 'Melyik gáz alkotja a légkör legnagyobb részét?', '[{"key":"A","text":"Oxigén","correct":false},{"key":"B","text":"Nitrogén","correct":true},{"key":"C","text":"Szén-dioxid","correct":false}]', 'B', 10, '{"A":35,"B":50,"C":15}', 'B', 'mixed'),
('science_161', 'Mi a vegyjele a szénnek?', '[{"key":"A","text":"S","correct":false},{"key":"B","text":"C","correct":true},{"key":"C","text":"Ca","correct":false}]', 'B', 10, '{"A":20,"B":65,"C":15}', 'B', 'mixed'),
('science_162', 'Ki fedezte fel a penicillint?', '[{"key":"A","text":"Louis Pasteur","correct":false},{"key":"B","text":"Alexander Fleming","correct":true},{"key":"C","text":"Marie Curie","correct":false}]', 'B', 10, '{"A":25,"B":55,"C":20}', 'B', 'mixed'),
('science_163', 'Hány kromoszóma van egy emberi sejtben?', '[{"key":"A","text":"23","correct":false},{"key":"B","text":"46","correct":true},{"key":"C","text":"92","correct":false}]', 'B', 10, '{"A":30,"B":55,"C":15}', 'B', 'mixed'),
('science_164', 'Mi a vegyjele az oxigénnek?', '[{"key":"A","text":"Ox","correct":false},{"key":"B","text":"O","correct":true},{"key":"C","text":"O2","correct":false}]', 'B', 10, '{"A":15,"B":70,"C":15}', 'B', 'mixed'),
('science_165', 'Melyik bolygó a legközelebb a Naphoz?', '[{"key":"A","text":"Vénusz","correct":false},{"key":"B","text":"Merkúr","correct":true},{"key":"C","text":"Mars","correct":false}]', 'B', 10, '{"A":25,"B":60,"C":15}', 'B', 'mixed'),
('science_166', 'Mi az emberi test legnagyobb szerve?', '[{"key":"A","text":"Máj","correct":false},{"key":"B","text":"Bőr","correct":true},{"key":"C","text":"Tüdő","correct":false}]', 'B', 10, '{"A":30,"B":55,"C":15}', 'B', 'mixed'),
('science_167', 'Ki fogalmazta meg a relativitáselméletet?', '[{"key":"A","text":"Isaac Newton","correct":false},{"key":"B","text":"Albert Einstein","correct":true},{"key":"C","text":"Stephen Hawking","correct":false}]', 'B', 10, '{"A":15,"B":75,"C":10}', 'B', 'mixed'),
('science_168', 'Mi a vegyjele a vasnak?', '[{"key":"A","text":"V","correct":false},{"key":"B","text":"Fe","correct":true},{"key":"C","text":"Ir","correct":false}]', 'B', 10, '{"A":25,"B":55,"C":20}', 'B', 'mixed'),
('science_169', 'Hány percig tart a Föld egy teljes forgása a tengelye körül?', '[{"key":"A","text":"1340","correct":false},{"key":"B","text":"1440","correct":true},{"key":"C","text":"1540","correct":false}]', 'B', 10, '{"A":30,"B":45,"C":25}', 'B', 'mixed'),
('science_170', 'Mi a legkönnyebb elem a periódusos rendszerben?', '[{"key":"A","text":"Hélium","correct":false},{"key":"B","text":"Hidrogén","correct":true},{"key":"C","text":"Lítium","correct":false}]', 'B', 10, '{"A":30,"B":55,"C":15}', 'B', 'mixed'),
('science_171', 'Melyik szerv termeli az inzulint?', '[{"key":"A","text":"Máj","correct":false},{"key":"B","text":"Hasnyálmirigy","correct":true},{"key":"C","text":"Vese","correct":false}]', 'B', 10, '{"A":25,"B":55,"C":20}', 'B', 'mixed'),
('science_172', 'Mi a vegyjele a nátrium-kloridnak (konyhasó)?', '[{"key":"A","text":"NaCO3","correct":false},{"key":"B","text":"NaCl","correct":true},{"key":"C","text":"Na2O","correct":false}]', 'B', 10, '{"A":20,"B":60,"C":20}', 'B', 'mixed'),
('science_173', 'Ki találta fel a villanykörte praktikus változatát?', '[{"key":"A","text":"Nikola Tesla","correct":false},{"key":"B","text":"Thomas Edison","correct":true},{"key":"C","text":"Benjamin Franklin","correct":false}]', 'B', 10, '{"A":20,"B":65,"C":15}', 'B', 'mixed'),
('science_174', 'Mi a Nap legfőbb energiaforrása?', '[{"key":"A","text":"Maghasadás","correct":false},{"key":"B","text":"Magfúzió","correct":true},{"key":"C","text":"Kémiai reakció","correct":false}]', 'B', 10, '{"A":30,"B":50,"C":20}', 'B', 'mixed'),
('science_175', 'Melyik vitamin hiánya okoz skorbut betegséget?', '[{"key":"A","text":"B vitamin","correct":false},{"key":"B","text":"C vitamin","correct":true},{"key":"C","text":"D vitamin","correct":false}]', 'B', 10, '{"A":25,"B":55,"C":20}', 'B', 'mixed'),
('science_176', 'Mi a vegyjele a higanynak?', '[{"key":"A","text":"Hi","correct":false},{"key":"B","text":"Hg","correct":true},{"key":"C","text":"Hy","correct":false}]', 'B', 10, '{"A":30,"B":50,"C":20}', 'B', 'mixed'),
('science_177', 'Hány fok Celsiusban fagy meg a víz?', '[{"key":"A","text":"-10","correct":false},{"key":"B","text":"0","correct":true},{"key":"C","text":"10","correct":false}]', 'B', 10, '{"A":5,"B":90,"C":5}', 'B', 'mixed'),
('science_178', 'Mi a legkeményebb természetes anyag?', '[{"key":"A","text":"Kvarc","correct":false},{"key":"B","text":"Gyémánt","correct":true},{"key":"C","text":"Rubin","correct":false}]', 'B', 10, '{"A":15,"B":75,"C":10}', 'B', 'mixed'),
('science_179', 'Melyik bolygónak van a legtöbb holdja?', '[{"key":"A","text":"Jupiter","correct":false},{"key":"B","text":"Szaturnusz","correct":true},{"key":"C","text":"Uránusz","correct":false}]', 'B', 10, '{"A":40,"B":40,"C":20}', 'B', 'mixed'),
('science_180', 'Mi az atom központi része?', '[{"key":"A","text":"Elektron","correct":false},{"key":"B","text":"Atommag","correct":true},{"key":"C","text":"Neutron","correct":false}]', 'B', 10, '{"A":20,"B":60,"C":20}', 'B', 'mixed'),
('science_181', 'Ki fedezte fel a gravitációt?', '[{"key":"A","text":"Galileo Galilei","correct":false},{"key":"B","text":"Isaac Newton","correct":true},{"key":"C","text":"Johannes Kepler","correct":false}]', 'B', 10, '{"A":20,"B":70,"C":10}', 'B', 'mixed'),
('science_182', 'Mi a vegyjele az ezüstnek?', '[{"key":"A","text":"Au","correct":false},{"key":"B","text":"Ag","correct":true},{"key":"C","text":"Ez","correct":false}]', 'B', 10, '{"A":30,"B":50,"C":20}', 'B', 'mixed'),
('science_183', 'Hány fok Fahrenheit a víz forráspontja?', '[{"key":"A","text":"180","correct":false},{"key":"B","text":"212","correct":true},{"key":"C","text":"250","correct":false}]', 'B', 10, '{"A":25,"B":50,"C":25}', 'B', 'mixed'),
('science_184', 'Melyik szerv felelős a vér szűréséért?', '[{"key":"A","text":"Máj","correct":false},{"key":"B","text":"Vese","correct":true},{"key":"C","text":"Szív","correct":false}]', 'B', 10, '{"A":30,"B":55,"C":15}', 'B', 'mixed'),
('science_185', 'Mi a pH értéke a tiszta víznek?', '[{"key":"A","text":"5","correct":false},{"key":"B","text":"7","correct":true},{"key":"C","text":"9","correct":false}]', 'B', 10, '{"A":20,"B":65,"C":15}', 'B', 'mixed'),
('science_186', 'Melyik elem a leggyakoribb az univerzumban?', '[{"key":"A","text":"Oxigén","correct":false},{"key":"B","text":"Hidrogén","correct":true},{"key":"C","text":"Hélium","correct":false}]', 'B', 10, '{"A":25,"B":55,"C":20}', 'B', 'mixed'),
('science_187', 'Mi a vegyjele a réznek?', '[{"key":"A","text":"Re","correct":false},{"key":"B","text":"Cu","correct":true},{"key":"C","text":"Co","correct":false}]', 'B', 10, '{"A":25,"B":50,"C":25}', 'B', 'mixed'),
('science_188', 'Hány Celsius fok a víz forráspontja tengerszinten?', '[{"key":"A","text":"90","correct":false},{"key":"B","text":"100","correct":true},{"key":"C","text":"110","correct":false}]', 'B', 10, '{"A":10,"B":80,"C":10}', 'B', 'mixed'),
('science_189', 'Mi az emberi agy átlagos súlya?', '[{"key":"A","text":"1 kg","correct":false},{"key":"B","text":"1,4 kg","correct":true},{"key":"C","text":"2 kg","correct":false}]', 'B', 10, '{"A":25,"B":55,"C":20}', 'B', 'mixed'),
('science_190', 'Melyik tudós fedezte fel a radioaktivitást?', '[{"key":"A","text":"Albert Einstein","correct":false},{"key":"B","text":"Marie Curie","correct":true},{"key":"C","text":"Niels Bohr","correct":false}]', 'B', 10, '{"A":20,"B":60,"C":20}', 'B', 'mixed'),
('science_191', 'Mi a vegyjele az ólomnak?', '[{"key":"A","text":"O","correct":false},{"key":"B","text":"Pb","correct":true},{"key":"C","text":"Ol","correct":false}]', 'B', 10, '{"A":25,"B":50,"C":25}', 'B', 'mixed'),
('science_192', 'Hány liter vér van egy átlagos felnőtt emberben?', '[{"key":"A","text":"3-4","correct":false},{"key":"B","text":"5-6","correct":true},{"key":"C","text":"7-8","correct":false}]', 'B', 10, '{"A":25,"B":55,"C":20}', 'B', 'mixed'),
('science_193', 'Mi a leggyakoribb vércsoport világszerte?', '[{"key":"A","text":"A","correct":false},{"key":"B","text":"O","correct":true},{"key":"C","text":"B","correct":false}]', 'B', 10, '{"A":30,"B":50,"C":20}', 'B', 'mixed'),
('science_194', 'Melyik bolygót nevezik a Vörös Bolygónak?', '[{"key":"A","text":"Vénusz","correct":false},{"key":"B","text":"Mars","correct":true},{"key":"C","text":"Jupiter","correct":false}]', 'B', 10, '{"A":10,"B":80,"C":10}', 'B', 'mixed'),
('science_195', 'Mi a vegyjele a káliumnak?', '[{"key":"A","text":"Ka","correct":false},{"key":"B","text":"K","correct":true},{"key":"C","text":"Kl","correct":false}]', 'B', 10, '{"A":25,"B":55,"C":20}', 'B', 'mixed'),
('science_196', 'Ki találta fel a dinamitot?', '[{"key":"A","text":"Albert Nobel","correct":false},{"key":"B","text":"Alfred Nobel","correct":true},{"key":"C","text":"Albert Einstein","correct":false}]', 'B', 10, '{"A":30,"B":55,"C":15}', 'B', 'mixed'),
('science_197', 'Mi a Naprendszer legforróbb bolygója?', '[{"key":"A","text":"Merkúr","correct":false},{"key":"B","text":"Vénusz","correct":true},{"key":"C","text":"Mars","correct":false}]', 'B', 10, '{"A":40,"B":45,"C":15}', 'B', 'mixed'),
('science_198', 'Hány csigolya van az emberi gerincben?', '[{"key":"A","text":"26","correct":false},{"key":"B","text":"33","correct":true},{"key":"C","text":"40","correct":false}]', 'B', 10, '{"A":30,"B":45,"C":25}', 'B', 'mixed'),
('science_199', 'Mi a vegyjele a nitrogénnek?', '[{"key":"A","text":"Ni","correct":false},{"key":"B","text":"N","correct":true},{"key":"C","text":"No","correct":false}]', 'B', 10, '{"A":25,"B":55,"C":20}', 'B', 'mixed'),
('science_200', 'Melyik szerv tárol glükózt glikogén formájában?', '[{"key":"A","text":"Vese","correct":false},{"key":"B","text":"Máj","correct":true},{"key":"C","text":"Lép","correct":false}]', 'B', 10, '{"A":25,"B":55,"C":20}', 'B', 'mixed');

-- Topic 10 fordítások (science_151 - science_200)
INSERT INTO question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c) VALUES
('science_151', 'hu', 'Mi a vegyjele a víznek?', 'CO2', 'H2O', 'O2'),
('science_151', 'en', 'What is the chemical symbol for water?', 'CO2', 'H2O', 'O2'),
('science_152', 'hu', 'Hány bolygó van a Naprendszerben?', '7', '8', '9'),
('science_152', 'en', 'How many planets are in the Solar System?', '7', '8', '9'),
('science_153', 'hu', 'Mi a fény sebessége vákuumban?', '200 000 km/s', '300 000 km/s', '400 000 km/s'),
('science_153', 'en', 'What is the speed of light in vacuum?', '200,000 km/s', '300,000 km/s', '400,000 km/s'),
('science_154', 'hu', 'Mi az emberi test legkisebb csontja?', 'Kalapács', 'Kengyel', 'Üllő'),
('science_154', 'en', 'What is the smallest bone in the human body?', 'Hammer', 'Stapes', 'Anvil'),
('science_155', 'hu', 'Mi a DNA rövidítés jelentése?', 'Dinukleotid Acid', 'Dezoxiribonukleinsav', 'Dinukleáris Anyag'),
('science_155', 'en', 'What does DNA stand for?', 'Dinucleotide Acid', 'Deoxyribonucleic Acid', 'Dinuclear Material'),
('science_156', 'hu', 'Melyik a legnagyobb bolygó a Naprendszerben?', 'Szaturnusz', 'Jupiter', 'Neptunusz'),
('science_156', 'en', 'Which is the largest planet in the Solar System?', 'Saturn', 'Jupiter', 'Neptune'),
('science_157', 'hu', 'Mi a vegyjele az aranynak?', 'Ag', 'Au', 'Ar'),
('science_157', 'en', 'What is the chemical symbol for gold?', 'Ag', 'Au', 'Ar'),
('science_158', 'hu', 'Hány csont van a felnőtt emberi testben?', '186', '206', '226'),
('science_158', 'en', 'How many bones are in the adult human body?', '186', '206', '226'),
('science_159', 'hu', 'Mi a Föld legbelső rétege?', 'Köpeny', 'Mag', 'Kéreg'),
('science_159', 'en', 'What is the innermost layer of Earth?', 'Mantle', 'Core', 'Crust'),
('science_160', 'hu', 'Melyik gáz alkotja a légkör legnagyobb részét?', 'Oxigén', 'Nitrogén', 'Szén-dioxid'),
('science_160', 'en', 'Which gas makes up most of the atmosphere?', 'Oxygen', 'Nitrogen', 'Carbon dioxide'),
('science_161', 'hu', 'Mi a vegyjele a szénnek?', 'S', 'C', 'Ca'),
('science_161', 'en', 'What is the chemical symbol for carbon?', 'S', 'C', 'Ca'),
('science_162', 'hu', 'Ki fedezte fel a penicillint?', 'Louis Pasteur', 'Alexander Fleming', 'Marie Curie'),
('science_162', 'en', 'Who discovered penicillin?', 'Louis Pasteur', 'Alexander Fleming', 'Marie Curie'),
('science_163', 'hu', 'Hány kromoszóma van egy emberi sejtben?', '23', '46', '92'),
('science_163', 'en', 'How many chromosomes are in a human cell?', '23', '46', '92'),
('science_164', 'hu', 'Mi a vegyjele az oxigénnek?', 'Ox', 'O', 'O2'),
('science_164', 'en', 'What is the chemical symbol for oxygen?', 'Ox', 'O', 'O2'),
('science_165', 'hu', 'Melyik bolygó a legközelebb a Naphoz?', 'Vénusz', 'Merkúr', 'Mars'),
('science_165', 'en', 'Which planet is closest to the Sun?', 'Venus', 'Mercury', 'Mars'),
('science_166', 'hu', 'Mi az emberi test legnagyobb szerve?', 'Máj', 'Bőr', 'Tüdő'),
('science_166', 'en', 'What is the largest organ in the human body?', 'Liver', 'Skin', 'Lungs'),
('science_167', 'hu', 'Ki fogalmazta meg a relativitáselméletet?', 'Isaac Newton', 'Albert Einstein', 'Stephen Hawking'),
('science_167', 'en', 'Who formulated the theory of relativity?', 'Isaac Newton', 'Albert Einstein', 'Stephen Hawking'),
('science_168', 'hu', 'Mi a vegyjele a vasnak?', 'V', 'Fe', 'Ir'),
('science_168', 'en', 'What is the chemical symbol for iron?', 'V', 'Fe', 'Ir'),
('science_169', 'hu', 'Hány percig tart a Föld egy teljes forgása a tengelye körül?', '1340', '1440', '1540'),
('science_169', 'en', 'How many minutes does it take for Earth to complete one rotation?', '1340', '1440', '1540'),
('science_170', 'hu', 'Mi a legkönnyebb elem a periódusos rendszerben?', 'Hélium', 'Hidrogén', 'Lítium'),
('science_170', 'en', 'What is the lightest element in the periodic table?', 'Helium', 'Hydrogen', 'Lithium'),
('science_171', 'hu', 'Melyik szerv termeli az inzulint?', 'Máj', 'Hasnyálmirigy', 'Vese'),
('science_171', 'en', 'Which organ produces insulin?', 'Liver', 'Pancreas', 'Kidney'),
('science_172', 'hu', 'Mi a vegyjele a nátrium-kloridnak (konyhasó)?', 'NaCO3', 'NaCl', 'Na2O'),
('science_172', 'en', 'What is the chemical formula for sodium chloride (table salt)?', 'NaCO3', 'NaCl', 'Na2O'),
('science_173', 'hu', 'Ki találta fel a villanykörte praktikus változatát?', 'Nikola Tesla', 'Thomas Edison', 'Benjamin Franklin'),
('science_173', 'en', 'Who invented the practical light bulb?', 'Nikola Tesla', 'Thomas Edison', 'Benjamin Franklin'),
('science_174', 'hu', 'Mi a Nap legfőbb energiaforrása?', 'Maghasadás', 'Magfúzió', 'Kémiai reakció'),
('science_174', 'en', 'What is the Sun main energy source?', 'Nuclear fission', 'Nuclear fusion', 'Chemical reaction'),
('science_175', 'hu', 'Melyik vitamin hiánya okoz skorbut betegséget?', 'B vitamin', 'C vitamin', 'D vitamin'),
('science_175', 'en', 'Which vitamin deficiency causes scurvy?', 'Vitamin B', 'Vitamin C', 'Vitamin D'),
('science_176', 'hu', 'Mi a vegyjele a higanynak?', 'Hi', 'Hg', 'Hy'),
('science_176', 'en', 'What is the chemical symbol for mercury?', 'Hi', 'Hg', 'Hy'),
('science_177', 'hu', 'Hány fok Celsiusban fagy meg a víz?', '-10', '0', '10'),
('science_177', 'en', 'At what temperature in Celsius does water freeze?', '-10', '0', '10'),
('science_178', 'hu', 'Mi a legkeményebb természetes anyag?', 'Kvarc', 'Gyémánt', 'Rubin'),
('science_178', 'en', 'What is the hardest natural substance?', 'Quartz', 'Diamond', 'Ruby'),
('science_179', 'hu', 'Melyik bolygónak van a legtöbb holdja?', 'Jupiter', 'Szaturnusz', 'Uránusz'),
('science_179', 'en', 'Which planet has the most moons?', 'Jupiter', 'Saturn', 'Uranus'),
('science_180', 'hu', 'Mi az atom központi része?', 'Elektron', 'Atommag', 'Neutron'),
('science_180', 'en', 'What is the central part of an atom?', 'Electron', 'Nucleus', 'Neutron'),
('science_181', 'hu', 'Ki fedezte fel a gravitációt?', 'Galileo Galilei', 'Isaac Newton', 'Johannes Kepler'),
('science_181', 'en', 'Who discovered gravity?', 'Galileo Galilei', 'Isaac Newton', 'Johannes Kepler'),
('science_182', 'hu', 'Mi a vegyjele az ezüstnek?', 'Au', 'Ag', 'Ez'),
('science_182', 'en', 'What is the chemical symbol for silver?', 'Au', 'Ag', 'Si'),
('science_183', 'hu', 'Hány fok Fahrenheit a víz forráspontja?', '180', '212', '250'),
('science_183', 'en', 'What is the boiling point of water in Fahrenheit?', '180', '212', '250'),
('science_184', 'hu', 'Melyik szerv felelős a vér szűréséért?', 'Máj', 'Vese', 'Szív'),
('science_184', 'en', 'Which organ is responsible for filtering blood?', 'Liver', 'Kidney', 'Heart'),
('science_185', 'hu', 'Mi a pH értéke a tiszta víznek?', '5', '7', '9'),
('science_185', 'en', 'What is the pH value of pure water?', '5', '7', '9'),
('science_186', 'hu', 'Melyik elem a leggyakoribb az univerzumban?', 'Oxigén', 'Hidrogén', 'Hélium'),
('science_186', 'en', 'Which element is most abundant in the universe?', 'Oxygen', 'Hydrogen', 'Helium'),
('science_187', 'hu', 'Mi a vegyjele a réznek?', 'Re', 'Cu', 'Co'),
('science_187', 'en', 'What is the chemical symbol for copper?', 'Re', 'Cu', 'Co'),
('science_188', 'hu', 'Hány Celsius fok a víz forráspontja tengerszinten?', '90', '100', '110'),
('science_188', 'en', 'What is the boiling point of water at sea level in Celsius?', '90', '100', '110'),
('science_189', 'hu', 'Mi az emberi agy átlagos súlya?', '1 kg', '1,4 kg', '2 kg'),
('science_189', 'en', 'What is the average weight of the human brain?', '1 kg', '1.4 kg', '2 kg'),
('science_190', 'hu', 'Melyik tudós fedezte fel a radioaktivitást?', 'Albert Einstein', 'Marie Curie', 'Niels Bohr'),
('science_190', 'en', 'Which scientist discovered radioactivity?', 'Albert Einstein', 'Marie Curie', 'Niels Bohr'),
('science_191', 'hu', 'Mi a vegyjele az ólomnak?', 'O', 'Pb', 'Ol'),
('science_191', 'en', 'What is the chemical symbol for lead?', 'O', 'Pb', 'Le'),
('science_192', 'hu', 'Hány liter vér van egy átlagos felnőtt emberben?', '3-4', '5-6', '7-8'),
('science_192', 'en', 'How many liters of blood are in an average adult?', '3-4', '5-6', '7-8'),
('science_193', 'hu', 'Mi a leggyakoribb vércsoport világszerte?', 'A', 'O', 'B'),
('science_193', 'en', 'What is the most common blood type worldwide?', 'A', 'O', 'B'),
('science_194', 'hu', 'Melyik bolygót nevezik a Vörös Bolygónak?', 'Vénusz', 'Mars', 'Jupiter'),
('science_194', 'en', 'Which planet is called the Red Planet?', 'Venus', 'Mars', 'Jupiter'),
('science_195', 'hu', 'Mi a vegyjele a káliumnak?', 'Ka', 'K', 'Kl'),
('science_195', 'en', 'What is the chemical symbol for potassium?', 'Ka', 'K', 'Kl'),
('science_196', 'hu', 'Ki találta fel a dinamitot?', 'Albert Nobel', 'Alfred Nobel', 'Albert Einstein'),
('science_196', 'en', 'Who invented dynamite?', 'Albert Nobel', 'Alfred Nobel', 'Albert Einstein'),
('science_197', 'hu', 'Mi a Naprendszer legforróbb bolygója?', 'Merkúr', 'Vénusz', 'Mars'),
('science_197', 'en', 'What is the hottest planet in the Solar System?', 'Mercury', 'Venus', 'Mars'),
('science_198', 'hu', 'Hány csigolya van az emberi gerincben?', '26', '33', '40'),
('science_198', 'en', 'How many vertebrae are in the human spine?', '26', '33', '40'),
('science_199', 'hu', 'Mi a vegyjele a nitrogénnek?', 'Ni', 'N', 'No'),
('science_199', 'en', 'What is the chemical symbol for nitrogen?', 'Ni', 'N', 'No'),
('science_200', 'hu', 'Melyik szerv tárol glükózt glikogén formájában?', 'Vese', 'Máj', 'Lép'),
('science_200', 'en', 'Which organ stores glucose as glycogen?', 'Kidney', 'Liver', 'Spleen')
ON CONFLICT (question_id, lang) DO NOTHING;