
-- Topic 3: Táplálkozás (Nutrition) - 50 English translations (IDs 151-200)
INSERT INTO question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c) VALUES
('taplalkozas_151', 'en', 'What are the three main macronutrients?', 'Vitamins, minerals, water', 'Protein, carbs, fats', 'Fiber, sugar, salt'),
('taplalkozas_152', 'en', 'How many calories are in 1 gram of protein?', '2 kcal', '4 kcal', '9 kcal'),
('taplalkozas_153', 'en', 'What is the glycemic index?', 'Fat content', 'Blood sugar impact rate', 'Protein quality'),
('taplalkozas_154', 'en', 'Which food has the most protein per 100g?', 'Chicken breast', 'Apple', 'Rice'),
('taplalkozas_155', 'en', 'How many calories are in 1 gram of fat?', '4 kcal', '7 kcal', '9 kcal'),
('taplalkozas_156', 'en', 'What are omega-3 fatty acids?', 'Saturated fats', 'Essential unsaturated fatty acids', 'Trans fats'),
('taplalkozas_157', 'en', 'Which vitamin is found in citrus fruits?', 'Vitamin A', 'Vitamin C', 'Vitamin D'),
('taplalkozas_158', 'en', 'What is the recommended daily fiber intake?', '5g', '25-30g', '100g'),
('taplalkozas_159', 'en', 'Which mineral is important for bone health?', 'Iron', 'Calcium', 'Zinc'),
('taplalkozas_160', 'en', 'What are probiotics?', 'Harmful bacteria', 'Beneficial bacteria', 'Vitamins'),
('taplalkozas_161', 'en', 'How many calories are in 1 gram of carbohydrates?', '2 kcal', '4 kcal', '9 kcal'),
('taplalkozas_162', 'en', 'Which food is high in iron?', 'Milk', 'Spinach', 'Bread'),
('taplalkozas_163', 'en', 'What is BMR?', 'Maximum heart rate', 'Basal metabolic rate', 'Muscle mass'),
('taplalkozas_164', 'en', 'Which food contains complete protein?', 'Beans', 'Eggs', 'Rice'),
('taplalkozas_165', 'en', 'What is intermittent fasting?', 'Continuous eating', 'Timed eating windows', 'No drinking'),
('taplalkozas_166', 'en', 'Which vitamin is fat-soluble?', 'Vitamin C', 'Vitamin D', 'Vitamin B12'),
('taplalkozas_167', 'en', 'What is the daily recommended sodium intake?', '500mg', '2300mg', '10000mg'),
('taplalkozas_168', 'en', 'Which food is high in potassium?', 'Bread', 'Banana', 'Cheese'),
('taplalkozas_169', 'en', 'What are antioxidants?', 'Harmful substances', 'Cell-protecting compounds', 'Fats'),
('taplalkozas_170', 'en', 'How much water should you drink daily?', '0.5 liters', '2-3 liters', '10 liters'),
('taplalkozas_171', 'en', 'Which nutrient provides the most energy per gram?', 'Protein', 'Carbohydrates', 'Fat'),
('taplalkozas_172', 'en', 'What is the function of dietary fiber?', 'Energy', 'Digestive health', 'Building muscle'),
('taplalkozas_173', 'en', 'Which food is rich in omega-3?', 'Chicken', 'Salmon', 'Beef'),
('taplalkozas_174', 'en', 'What is a caloric deficit?', 'Eating more than burning', 'Burning more than eating', 'Equal intake and output'),
('taplalkozas_175', 'en', 'Which vitamin helps iron absorption?', 'Vitamin A', 'Vitamin C', 'Vitamin D'),
('taplalkozas_176', 'en', 'What are complex carbohydrates?', 'Simple sugars', 'Slowly digested starches', 'Fats'),
('taplalkozas_177', 'en', 'Which mineral is important for thyroid function?', 'Iron', 'Iodine', 'Zinc'),
('taplalkozas_178', 'en', 'What is the function of B vitamins?', 'Bone health', 'Energy metabolism', 'Eye health'),
('taplalkozas_179', 'en', 'Which food is a good source of calcium?', 'Meat', 'Dairy products', 'Oils'),
('taplalkozas_180', 'en', 'What is cholesterol?', 'A vitamin', 'A type of fat', 'A mineral'),
('taplalkozas_181', 'en', 'What are prebiotics?', 'Probiotics food', 'Food for beneficial bacteria', 'Antibiotics'),
('taplalkozas_182', 'en', 'Which food is high in vitamin E?', 'Nuts and seeds', 'Fish', 'Dairy'),
('taplalkozas_183', 'en', 'What is the thermic effect of food?', 'Food temperature', 'Calories burned digesting food', 'Cooking heat'),
('taplalkozas_184', 'en', 'Which mineral is important for muscle contraction?', 'Iron', 'Magnesium', 'Zinc'),
('taplalkozas_185', 'en', 'What are trans fats?', 'Healthy fats', 'Artificially hydrogenated fats', 'Plant fats'),
('taplalkozas_186', 'en', 'What is the recommended protein intake per kg for adults?', '0.3g', '0.8g', '3g'),
('taplalkozas_187', 'en', 'Which vitamin is important for eye health?', 'Vitamin A', 'Vitamin C', 'Vitamin D'),
('taplalkozas_188', 'en', 'What is a whole grain?', 'Refined grain', 'Grain with all parts intact', 'Ground grain'),
('taplalkozas_189', 'en', 'Which food is high in zinc?', 'Fruits', 'Oysters', 'Bread'),
('taplalkozas_190', 'en', 'What is satiety?', 'Hunger', 'Feeling full', 'Thirst'),
('taplalkozas_191', 'en', 'Which vitamin is produced in the gut?', 'Vitamin A', 'Vitamin K', 'Vitamin C'),
('taplalkozas_192', 'en', 'What is food combining?', 'Mixing all foods', 'Strategic pairing of foods', 'Only one food'),
('taplalkozas_193', 'en', 'Which mineral helps blood clotting?', 'Iron', 'Calcium', 'Zinc'),
('taplalkozas_194', 'en', 'What is the function of vitamin D?', 'Energy', 'Calcium absorption', 'Protein synthesis'),
('taplalkozas_195', 'en', 'Which food is a complete protein source?', 'Rice', 'Quinoa', 'Beans'),
('taplalkozas_196', 'en', 'What is metabolic rate?', 'Heart rate', 'Rate of calorie burning', 'Breathing rate'),
('taplalkozas_197', 'en', 'Which nutrient is essential for brain function?', 'Fiber', 'Omega-3', 'Iron'),
('taplalkozas_198', 'en', 'What is bioavailability?', 'Food freshness', 'How well nutrients are absorbed', 'Calorie count'),
('taplalkozas_199', 'en', 'Which food is high in folate?', 'Meat', 'Leafy greens', 'Dairy'),
('taplalkozas_200', 'en', 'What is the glycemic load?', 'Total carbs', 'GI adjusted for serving size', 'Sugar content')
ON CONFLICT (question_id, lang) DO NOTHING;
