-- Topic 19: Popkultúra (Pop Culture) - 50 new questions (151-200)
INSERT INTO questions (id, question, answers, audience, third, source_category, topic_id) VALUES
('pop_151', 'Ki a BTS együttes hazája?', '[{"key":"A","text":"Dél-Korea","correct":true},{"key":"B","text":"Japán","correct":false},{"key":"C","text":"Kína","correct":false}]', '{"A":88,"B":8,"C":4}', 'K-pop banda.', 'mixed', 19),
('pop_152', 'Melyik sorozat főszereplője Jon Snow?', '[{"key":"A","text":"Trónok harca","correct":true},{"key":"B","text":"Vikingek","correct":false},{"key":"C","text":"Witcher","correct":false}]', '{"A":85,"B":10,"C":5}', 'Kit Harington alakítja.', 'mixed', 19),
('pop_153', 'Ki Taylor Swift első Grammy-díjas albuma?', '[{"key":"A","text":"Fearless","correct":true},{"key":"B","text":"Red","correct":false},{"key":"C","text":"1989","correct":false}]', '{"A":62,"B":25,"C":13}', '2010-ben nyert.', 'mixed', 19),
('pop_154', 'Melyik videojáték főhőse Mario?', '[{"key":"A","text":"Super Mario Bros.","correct":true},{"key":"B","text":"Zelda","correct":false},{"key":"C","text":"Donkey Kong","correct":false}]', '{"A":90,"B":6,"C":4}', 'Nintendo karakter.', 'mixed', 19),
('pop_155', 'Ki az Avengers csapat vezetője a filmekben?', '[{"key":"A","text":"Amerika Kapitány","correct":true},{"key":"B","text":"Vasember","correct":false},{"key":"C","text":"Thor","correct":false}]', '{"A":55,"B":35,"C":10}', 'Chris Evans alakítja.', 'mixed', 19),
('pop_156', 'Melyik évben indult a Friends sorozat?', '[{"key":"A","text":"1994","correct":true},{"key":"B","text":"1996","correct":false},{"key":"C","text":"1992","correct":false}]', '{"A":65,"B":22,"C":13}', '10 évadot élt meg.', 'mixed', 19),
('pop_157', 'Ki a Harry Potter legjobb barátja?', '[{"key":"A","text":"Ron Weasley","correct":true},{"key":"B","text":"Neville Longbottom","correct":false},{"key":"C","text":"Draco Malfoy","correct":false}]', '{"A":90,"B":7,"C":3}', 'Rupert Grint alakítja.', 'mixed', 19),
('pop_158', 'Melyik banda énekese Freddie Mercury?', '[{"key":"A","text":"Queen","correct":true},{"key":"B","text":"The Beatles","correct":false},{"key":"C","text":"Led Zeppelin","correct":false}]', '{"A":92,"B":5,"C":3}', 'Bohemian Rhapsody.', 'mixed', 19),
('pop_159', 'Ki a Stranger Things főszereplője?', '[{"key":"A","text":"Millie Bobby Brown (Eleven)","correct":true},{"key":"B","text":"Winona Ryder","correct":false},{"key":"C","text":"Finn Wolfhard","correct":false}]', '{"A":72,"B":18,"C":10}', 'Netflix sorozat.', 'mixed', 19),
('pop_160', 'Melyik játék a Fortnite műfaja?', '[{"key":"A","text":"Battle Royale","correct":true},{"key":"B","text":"RPG","correct":false},{"key":"C","text":"Szimulátor","correct":false}]', '{"A":85,"B":10,"C":5}', 'Epic Games fejlesztette.', 'mixed', 19),
('pop_161', 'Ki Beyoncé férje?', '[{"key":"A","text":"Jay-Z","correct":true},{"key":"B","text":"Kanye West","correct":false},{"key":"C","text":"Drake","correct":false}]', '{"A":88,"B":8,"C":4}', 'Hiphop mogul.', 'mixed', 19),
('pop_162', 'Melyik sorozatban szerepel a TARDIS?', '[{"key":"A","text":"Doctor Who","correct":true},{"key":"B","text":"Star Trek","correct":false},{"key":"C","text":"Battlestar Galactica","correct":false}]', '{"A":78,"B":14,"C":8}', 'Időgép telefonfülke.', 'mixed', 19),
('pop_163', 'Ki a Minecraft fejlesztője?', '[{"key":"A","text":"Mojang (Markus Persson)","correct":true},{"key":"B","text":"Electronic Arts","correct":false},{"key":"C","text":"Ubisoft","correct":false}]', '{"A":75,"B":15,"C":10}', 'Sandbox játék.', 'mixed', 19),
('pop_164', 'Melyik anime főszereplője Naruto Uzumaki?', '[{"key":"A","text":"Naruto","correct":true},{"key":"B","text":"One Piece","correct":false},{"key":"C","text":"Dragon Ball","correct":false}]', '{"A":88,"B":8,"C":4}', 'Japán anime sorozat.', 'mixed', 19),
('pop_165', 'Ki énekel a Thriller című dalban?', '[{"key":"A","text":"Michael Jackson","correct":true},{"key":"B","text":"Prince","correct":false},{"key":"C","text":"Whitney Houston","correct":false}]', '{"A":92,"B":5,"C":3}', 'A popzene királya.', 'mixed', 19),
('pop_166', 'Melyik évben jelent meg az első iPhone?', '[{"key":"A","text":"2007","correct":true},{"key":"B","text":"2005","correct":false},{"key":"C","text":"2009","correct":false}]', '{"A":72,"B":18,"C":10}', 'Steve Jobs mutatta be.', 'mixed', 19),
('pop_167', 'Ki a Breaking Bad főszereplője?', '[{"key":"A","text":"Bryan Cranston (Walter White)","correct":true},{"key":"B","text":"Aaron Paul","correct":false},{"key":"C","text":"Bob Odenkirk","correct":false}]', '{"A":78,"B":14,"C":8}', 'Kémiatanárból drogbáró.', 'mixed', 19),
('pop_168', 'Melyik zenekar énekese Kurt Cobain volt?', '[{"key":"A","text":"Nirvana","correct":true},{"key":"B","text":"Pearl Jam","correct":false},{"key":"C","text":"Soundgarden","correct":false}]', '{"A":85,"B":10,"C":5}', 'Grunge legenda.', 'mixed', 19),
('pop_169', 'Ki Elon Musk cége az űrkutatásban?', '[{"key":"A","text":"SpaceX","correct":true},{"key":"B","text":"Blue Origin","correct":false},{"key":"C","text":"Virgin Galactic","correct":false}]', '{"A":85,"B":10,"C":5}', 'Rakétákat fejleszt.', 'mixed', 19),
('pop_170', 'Melyik sorozat játszódik Westeros világában?', '[{"key":"A","text":"Trónok harca","correct":true},{"key":"B","text":"A Gyűrűk Ura","correct":false},{"key":"C","text":"The Witcher","correct":false}]', '{"A":88,"B":8,"C":4}', 'George R.R. Martin műve.', 'mixed', 19),
('pop_171', 'Ki a legfiatalabb milliárdos lett 2019-ben?', '[{"key":"A","text":"Kylie Jenner","correct":true},{"key":"B","text":"Mark Zuckerberg","correct":false},{"key":"C","text":"Evan Spiegel","correct":false}]', '{"A":72,"B":18,"C":10}', 'Kozmetikai cégével.', 'mixed', 19),
('pop_172', 'Melyik játékkonzolt fejleszti a Sony?', '[{"key":"A","text":"PlayStation","correct":true},{"key":"B","text":"Xbox","correct":false},{"key":"C","text":"Nintendo Switch","correct":false}]', '{"A":88,"B":8,"C":4}', 'Japán vállalat.', 'mixed', 19),
('pop_173', 'Ki a Spider-Man legújabb filmes alakítója?', '[{"key":"A","text":"Tom Holland","correct":true},{"key":"B","text":"Andrew Garfield","correct":false},{"key":"C","text":"Tobey Maguire","correct":false}]', '{"A":82,"B":12,"C":6}', 'MCU verzió.', 'mixed', 19),
('pop_174', 'Melyik közösségi média platform a TikTok elődje?', '[{"key":"A","text":"Musical.ly","correct":true},{"key":"B","text":"Vine","correct":false},{"key":"C","text":"Instagram","correct":false}]', '{"A":62,"B":25,"C":13}', '2018-ban egyesültek.', 'mixed', 19),
('pop_175', 'Ki a Kardashian család legismertebb tagja?', '[{"key":"A","text":"Kim Kardashian","correct":true},{"key":"B","text":"Khloe Kardashian","correct":false},{"key":"C","text":"Kourtney Kardashian","correct":false}]', '{"A":85,"B":10,"C":5}', 'Reality TV sztár.', 'mixed', 19),
('pop_176', 'Melyik sorozatban szerepel a Demogorgon?', '[{"key":"A","text":"Stranger Things","correct":true},{"key":"B","text":"American Horror Story","correct":false},{"key":"C","text":"The Walking Dead","correct":false}]', '{"A":82,"B":12,"C":6}', 'Fejjel lefelé világ szörnye.', 'mixed', 19),
('pop_177', 'Ki a Grand Theft Auto sorozat fejlesztője?', '[{"key":"A","text":"Rockstar Games","correct":true},{"key":"B","text":"Activision","correct":false},{"key":"C","text":"EA Games","correct":false}]', '{"A":80,"B":12,"C":8}', 'Open world játék.', 'mixed', 19),
('pop_178', 'Melyik énekesnő az Single Ladies előadója?', '[{"key":"A","text":"Beyoncé","correct":true},{"key":"B","text":"Rihanna","correct":false},{"key":"C","text":"Lady Gaga","correct":false}]', '{"A":85,"B":10,"C":5}', '2008-as sláger.', 'mixed', 19),
('pop_179', 'Ki az MCU Thanos karakterét alakította?', '[{"key":"A","text":"Josh Brolin","correct":true},{"key":"B","text":"James Spader","correct":false},{"key":"C","text":"Michael B. Jordan","correct":false}]', '{"A":68,"B":20,"C":12}', 'CGI karakter.', 'mixed', 19),
('pop_180', 'Melyik anime a legrégebbi a felsoroltak közül?', '[{"key":"A","text":"Dragon Ball","correct":true},{"key":"B","text":"Naruto","correct":false},{"key":"C","text":"One Piece","correct":false}]', '{"A":72,"B":18,"C":10}', '1984-ben indult.', 'mixed', 19),
('pop_181', 'Ki a Tesla és SpaceX vezérigazgatója?', '[{"key":"A","text":"Elon Musk","correct":true},{"key":"B","text":"Jeff Bezos","correct":false},{"key":"C","text":"Bill Gates","correct":false}]', '{"A":92,"B":5,"C":3}', 'Tech milliárdos.', 'mixed', 19),
('pop_182', 'Melyik film indította az MCU-t?', '[{"key":"A","text":"Vasember (2008)","correct":true},{"key":"B","text":"Amerika Kapitány","correct":false},{"key":"C","text":"Thor","correct":false}]', '{"A":78,"B":14,"C":8}', 'Robert Downey Jr. főszereplésével.', 'mixed', 19),
('pop_183', 'Ki a Squid Game rendezője?', '[{"key":"A","text":"Hwang Dong-hyuk","correct":true},{"key":"B","text":"Bong Joon-ho","correct":false},{"key":"C","text":"Park Chan-wook","correct":false}]', '{"A":55,"B":30,"C":15}', 'Koreai Netflix sorozat.', 'mixed', 19),
('pop_184', 'Melyik énekes a Shape of You előadója?', '[{"key":"A","text":"Ed Sheeran","correct":true},{"key":"B","text":"Justin Bieber","correct":false},{"key":"C","text":"Shawn Mendes","correct":false}]', '{"A":85,"B":10,"C":5}', '2017-es sláger.', 'mixed', 19),
('pop_185', 'Ki a The Office amerikai sorozat főszereplője?', '[{"key":"A","text":"Steve Carell","correct":true},{"key":"B","text":"Rainn Wilson","correct":false},{"key":"C","text":"John Krasinski","correct":false}]', '{"A":78,"B":14,"C":8}', 'Michael Scott karaktere.', 'mixed', 19),
('pop_186', 'Melyik játék a League of Legends műfaja?', '[{"key":"A","text":"MOBA","correct":true},{"key":"B","text":"FPS","correct":false},{"key":"C","text":"Battle Royale","correct":false}]', '{"A":75,"B":15,"C":10}', 'Riot Games fejlesztette.', 'mixed', 19),
('pop_187', 'Ki a Grammy-díjas Billie Eilish teljes neve?', '[{"key":"A","text":"Billie Eilish Pirate Baird O''Connell","correct":true},{"key":"B","text":"Billie Eilish Smith","correct":false},{"key":"C","text":"Billie Eilish Johnson","correct":false}]', '{"A":55,"B":28,"C":17}', 'Amerikai énekesnő.', 'mixed', 19),
('pop_188', 'Melyik streaming platform a House of Cards-ot?', '[{"key":"A","text":"Netflix","correct":true},{"key":"B","text":"HBO Max","correct":false},{"key":"C","text":"Amazon Prime","correct":false}]', '{"A":82,"B":12,"C":6}', 'Kevin Spacey főszereplésével.', 'mixed', 19),
('pop_189', 'Ki a Pokémon sorozat főhőse?', '[{"key":"A","text":"Ash Ketchum","correct":true},{"key":"B","text":"Red","correct":false},{"key":"C","text":"Brock","correct":false}]', '{"A":85,"B":10,"C":5}', 'Pikachu gazdája.', 'mixed', 19),
('pop_190', 'Melyik rapper neve Marshall Mathers?', '[{"key":"A","text":"Eminem","correct":true},{"key":"B","text":"Jay-Z","correct":false},{"key":"C","text":"50 Cent","correct":false}]', '{"A":88,"B":8,"C":4}', 'Slim Shady.', 'mixed', 19),
('pop_191', 'Ki a Wednesday sorozat főszereplője?', '[{"key":"A","text":"Jenna Ortega","correct":true},{"key":"B","text":"Christina Ricci","correct":false},{"key":"C","text":"Emma Myers","correct":false}]', '{"A":78,"B":14,"C":8}', 'Tim Burton rendezte.', 'mixed', 19),
('pop_192', 'Melyik közösségi média platform Evan Spiegelé?', '[{"key":"A","text":"Snapchat","correct":true},{"key":"B","text":"Instagram","correct":false},{"key":"C","text":"TikTok","correct":false}]', '{"A":72,"B":18,"C":10}', 'Eltűnő üzenetek.', 'mixed', 19),
('pop_193', 'Ki a The Mandalorian főszereplője?', '[{"key":"A","text":"Pedro Pascal","correct":true},{"key":"B","text":"Oscar Isaac","correct":false},{"key":"C","text":"Diego Luna","correct":false}]', '{"A":75,"B":15,"C":10}', 'Baby Yoda gazdája.', 'mixed', 19),
('pop_194', 'Melyik játék a Call of Duty műfaja?', '[{"key":"A","text":"FPS (First Person Shooter)","correct":true},{"key":"B","text":"RPG","correct":false},{"key":"C","text":"Stratégia","correct":false}]', '{"A":85,"B":10,"C":5}', 'Activision fejlesztette.', 'mixed', 19),
('pop_195', 'Ki Lady Gaga eredeti neve?', '[{"key":"A","text":"Stefani Joanne Angelina Germanotta","correct":true},{"key":"B","text":"Stefani Marie Cooper","correct":false},{"key":"C","text":"Joanne Lady Smith","correct":false}]', '{"A":65,"B":22,"C":13}', 'Olasz származású.', 'mixed', 19),
('pop_196', 'Melyik sorozat főszereplője Sherlock Holmes Benedict Cumberbatch?', '[{"key":"A","text":"Sherlock","correct":true},{"key":"B","text":"Elementary","correct":false},{"key":"C","text":"House","correct":false}]', '{"A":85,"B":10,"C":5}', 'BBC sorozat.', 'mixed', 19),
('pop_197', 'Ki a Meta (Facebook) alapítója?', '[{"key":"A","text":"Mark Zuckerberg","correct":true},{"key":"B","text":"Jack Dorsey","correct":false},{"key":"C","text":"Evan Spiegel","correct":false}]', '{"A":92,"B":5,"C":3}', 'Harvardi diákként alapította.', 'mixed', 19),
('pop_198', 'Melyik anime főhőse Luffy?', '[{"key":"A","text":"One Piece","correct":true},{"key":"B","text":"Naruto","correct":false},{"key":"C","text":"Bleach","correct":false}]', '{"A":82,"B":12,"C":6}', 'Kalózos anime.', 'mixed', 19),
('pop_199', 'Ki a Barbie film 2023-as főszereplője?', '[{"key":"A","text":"Margot Robbie","correct":true},{"key":"B","text":"Ryan Gosling","correct":false},{"key":"C","text":"Emma Stone","correct":false}]', '{"A":85,"B":10,"C":5}', 'Greta Gerwig rendezte.', 'mixed', 19),
('pop_200', 'Melyik év a Marvel Endgame premierjének éve?', '[{"key":"A","text":"2019","correct":true},{"key":"B","text":"2018","correct":false},{"key":"C","text":"2020","correct":false}]', '{"A":78,"B":14,"C":8}', 'Infinity Saga zárófilmje.', 'mixed', 19);

-- English translations for Topic 19
INSERT INTO question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c, explanation) VALUES
('pop_151', 'en', 'What country is BTS from?', 'South Korea', 'Japan', 'China', 'K-pop band.'),
('pop_152', 'en', 'Which series features Jon Snow?', 'Game of Thrones', 'Vikings', 'The Witcher', 'Played by Kit Harington.'),
('pop_153', 'en', 'What was Taylor Swift''s first Grammy-winning album?', 'Fearless', 'Red', '1989', 'Won in 2010.'),
('pop_154', 'en', 'Which video game features Mario?', 'Super Mario Bros.', 'Zelda', 'Donkey Kong', 'Nintendo character.'),
('pop_155', 'en', 'Who leads the Avengers team in the films?', 'Captain America', 'Iron Man', 'Thor', 'Played by Chris Evans.'),
('pop_156', 'en', 'What year did Friends premiere?', '1994', '1996', '1992', 'Ran for 10 seasons.'),
('pop_157', 'en', 'Who is Harry Potter''s best friend?', 'Ron Weasley', 'Neville Longbottom', 'Draco Malfoy', 'Played by Rupert Grint.'),
('pop_158', 'en', 'Which band had Freddie Mercury as singer?', 'Queen', 'The Beatles', 'Led Zeppelin', 'Bohemian Rhapsody.'),
('pop_159', 'en', 'Who stars in Stranger Things?', 'Millie Bobby Brown (Eleven)', 'Winona Ryder', 'Finn Wolfhard', 'Netflix series.'),
('pop_160', 'en', 'What genre is Fortnite?', 'Battle Royale', 'RPG', 'Simulator', 'Developed by Epic Games.'),
('pop_161', 'en', 'Who is Beyoncé married to?', 'Jay-Z', 'Kanye West', 'Drake', 'Hip-hop mogul.'),
('pop_162', 'en', 'Which series features the TARDIS?', 'Doctor Who', 'Star Trek', 'Battlestar Galactica', 'Time machine phone booth.'),
('pop_163', 'en', 'Who developed Minecraft?', 'Mojang (Markus Persson)', 'Electronic Arts', 'Ubisoft', 'Sandbox game.'),
('pop_164', 'en', 'Which anime features Naruto Uzumaki?', 'Naruto', 'One Piece', 'Dragon Ball', 'Japanese anime series.'),
('pop_165', 'en', 'Who sings Thriller?', 'Michael Jackson', 'Prince', 'Whitney Houston', 'King of Pop.'),
('pop_166', 'en', 'What year was the first iPhone released?', '2007', '2005', '2009', 'Steve Jobs unveiled it.'),
('pop_167', 'en', 'Who stars in Breaking Bad?', 'Bryan Cranston (Walter White)', 'Aaron Paul', 'Bob Odenkirk', 'Chemistry teacher to drug lord.'),
('pop_168', 'en', 'Which band had Kurt Cobain as singer?', 'Nirvana', 'Pearl Jam', 'Soundgarden', 'Grunge legend.'),
('pop_169', 'en', 'What is Elon Musk''s space company?', 'SpaceX', 'Blue Origin', 'Virgin Galactic', 'Develops rockets.'),
('pop_170', 'en', 'Which series is set in Westeros?', 'Game of Thrones', 'Lord of the Rings', 'The Witcher', 'George R.R. Martin''s work.'),
('pop_171', 'en', 'Who became the youngest billionaire in 2019?', 'Kylie Jenner', 'Mark Zuckerberg', 'Evan Spiegel', 'Through her cosmetics company.'),
('pop_172', 'en', 'Which game console does Sony develop?', 'PlayStation', 'Xbox', 'Nintendo Switch', 'Japanese company.'),
('pop_173', 'en', 'Who is the latest Spider-Man actor?', 'Tom Holland', 'Andrew Garfield', 'Tobey Maguire', 'MCU version.'),
('pop_174', 'en', 'What app was TikTok''s predecessor?', 'Musical.ly', 'Vine', 'Instagram', 'Merged in 2018.'),
('pop_175', 'en', 'Who is the most famous Kardashian?', 'Kim Kardashian', 'Khloe Kardashian', 'Kourtney Kardashian', 'Reality TV star.'),
('pop_176', 'en', 'Which series features the Demogorgon?', 'Stranger Things', 'American Horror Story', 'The Walking Dead', 'Upside Down monster.'),
('pop_177', 'en', 'Who develops Grand Theft Auto?', 'Rockstar Games', 'Activision', 'EA Games', 'Open world game.'),
('pop_178', 'en', 'Which singer performs Single Ladies?', 'Beyoncé', 'Rihanna', 'Lady Gaga', '2008 hit.'),
('pop_179', 'en', 'Who plays Thanos in the MCU?', 'Josh Brolin', 'James Spader', 'Michael B. Jordan', 'CGI character.'),
('pop_180', 'en', 'Which anime is the oldest listed?', 'Dragon Ball', 'Naruto', 'One Piece', 'Started in 1984.'),
('pop_181', 'en', 'Who is the CEO of Tesla and SpaceX?', 'Elon Musk', 'Jeff Bezos', 'Bill Gates', 'Tech billionaire.'),
('pop_182', 'en', 'Which film started the MCU?', 'Iron Man (2008)', 'Captain America', 'Thor', 'Starring Robert Downey Jr.'),
('pop_183', 'en', 'Who directed Squid Game?', 'Hwang Dong-hyuk', 'Bong Joon-ho', 'Park Chan-wook', 'Korean Netflix series.'),
('pop_184', 'en', 'Who sings Shape of You?', 'Ed Sheeran', 'Justin Bieber', 'Shawn Mendes', '2017 hit.'),
('pop_185', 'en', 'Who stars in The Office (US)?', 'Steve Carell', 'Rainn Wilson', 'John Krasinski', 'Michael Scott character.'),
('pop_186', 'en', 'What genre is League of Legends?', 'MOBA', 'FPS', 'Battle Royale', 'Developed by Riot Games.'),
('pop_187', 'en', 'What is Billie Eilish''s full name?', 'Billie Eilish Pirate Baird O''Connell', 'Billie Eilish Smith', 'Billie Eilish Johnson', 'American singer.'),
('pop_188', 'en', 'Which streaming platform made House of Cards?', 'Netflix', 'HBO Max', 'Amazon Prime', 'Starring Kevin Spacey.'),
('pop_189', 'en', 'Who is the protagonist of Pokémon?', 'Ash Ketchum', 'Red', 'Brock', 'Pikachu''s trainer.'),
('pop_190', 'en', 'Which rapper''s name is Marshall Mathers?', 'Eminem', 'Jay-Z', '50 Cent', 'Slim Shady.'),
('pop_191', 'en', 'Who stars in Wednesday?', 'Jenna Ortega', 'Christina Ricci', 'Emma Myers', 'Directed by Tim Burton.'),
('pop_192', 'en', 'Which social media did Evan Spiegel create?', 'Snapchat', 'Instagram', 'TikTok', 'Disappearing messages.'),
('pop_193', 'en', 'Who stars in The Mandalorian?', 'Pedro Pascal', 'Oscar Isaac', 'Diego Luna', 'Baby Yoda''s guardian.'),
('pop_194', 'en', 'What genre is Call of Duty?', 'FPS (First Person Shooter)', 'RPG', 'Strategy', 'Developed by Activision.'),
('pop_195', 'en', 'What is Lady Gaga''s real name?', 'Stefani Joanne Angelina Germanotta', 'Stefani Marie Cooper', 'Joanne Lady Smith', 'Italian descent.'),
('pop_196', 'en', 'Which series stars Benedict Cumberbatch as Sherlock?', 'Sherlock', 'Elementary', 'House', 'BBC series.'),
('pop_197', 'en', 'Who founded Meta (Facebook)?', 'Mark Zuckerberg', 'Jack Dorsey', 'Evan Spiegel', 'Founded as Harvard student.'),
('pop_198', 'en', 'Which anime features Luffy?', 'One Piece', 'Naruto', 'Bleach', 'Pirate anime.'),
('pop_199', 'en', 'Who stars in Barbie (2023)?', 'Margot Robbie', 'Ryan Gosling', 'Emma Stone', 'Directed by Greta Gerwig.'),
('pop_200', 'en', 'What year did Avengers: Endgame premiere?', '2019', '2018', '2020', 'Infinity Saga finale.');