-- Topic 8 (Sport) - 25 új kérdés (sport_051 - sport_075)
INSERT INTO questions (id, question, answers, correct_answer, topic_id, audience, third, source_category) VALUES
('sport_051', 'Melyik csapat nyerte a legtöbb NBA bajnoki címet?', '[{"key":"A","text":"Los Angeles Lakers","correct":false},{"key":"B","text":"Boston Celtics","correct":true},{"key":"C","text":"Chicago Bulls","correct":false}]', 'B', 8, '{"A":35,"B":50,"C":15}', 'B', 'mixed'),
('sport_052', 'Hány pont egy touchdown az amerikai futballban?', '[{"key":"A","text":"5","correct":false},{"key":"B","text":"6","correct":true},{"key":"C","text":"7","correct":false}]', 'B', 8, '{"A":20,"B":65,"C":15}', 'B', 'mixed'),
('sport_053', 'Melyik országban rendezték az első téli olimpiát?', '[{"key":"A","text":"Svájc","correct":false},{"key":"B","text":"Franciaország","correct":true},{"key":"C","text":"Ausztria","correct":false}]', 'B', 8, '{"A":30,"B":55,"C":15}', 'B', 'mixed'),
('sport_054', 'Hány lyukból áll egy standard golf pálya?', '[{"key":"A","text":"16","correct":false},{"key":"B","text":"18","correct":true},{"key":"C","text":"20","correct":false}]', 'B', 8, '{"A":15,"B":75,"C":10}', 'B', 'mixed'),
('sport_055', 'Melyik sportágban használnak puck-ot?', '[{"key":"A","text":"Jégkorong","correct":true},{"key":"B","text":"Floorball","correct":false},{"key":"C","text":"Gyeplabda","correct":false}]', 'A', 8, '{"A":80,"B":10,"C":10}', 'A', 'mixed'),
('sport_056', 'Ki a valaha volt leggyorsabb futó a 100 méteren?', '[{"key":"A","text":"Carl Lewis","correct":false},{"key":"B","text":"Usain Bolt","correct":true},{"key":"C","text":"Justin Gatlin","correct":false}]', 'B', 8, '{"A":15,"B":80,"C":5}', 'B', 'mixed'),
('sport_057', 'Hány játékos van egy röplabdacsapatban a pályán?', '[{"key":"A","text":"5","correct":false},{"key":"B","text":"6","correct":true},{"key":"C","text":"7","correct":false}]', 'B', 8, '{"A":20,"B":70,"C":10}', 'B', 'mixed'),
('sport_058', 'Melyik sportágban versenyeznek a Tour de France-on?', '[{"key":"A","text":"Futás","correct":false},{"key":"B","text":"Kerékpározás","correct":true},{"key":"C","text":"Triatlon","correct":false}]', 'B', 8, '{"A":5,"B":90,"C":5}', 'B', 'mixed'),
('sport_059', 'Hány félidőből áll egy kosárlabda mérkőzés?', '[{"key":"A","text":"2","correct":false},{"key":"B","text":"4","correct":true},{"key":"C","text":"3","correct":false}]', 'B', 8, '{"A":25,"B":60,"C":15}', 'B', 'mixed'),
('sport_060', 'Melyik országból származik a sumo birkózás?', '[{"key":"A","text":"Kína","correct":false},{"key":"B","text":"Japán","correct":true},{"key":"C","text":"Korea","correct":false}]', 'B', 8, '{"A":10,"B":85,"C":5}', 'B', 'mixed'),
('sport_061', 'Mi a neve a teniszben a 40-40 állásnak?', '[{"key":"A","text":"Egyenlítés","correct":false},{"key":"B","text":"Deuce","correct":true},{"key":"C","text":"Advantage","correct":false}]', 'B', 8, '{"A":20,"B":70,"C":10}', 'B', 'mixed'),
('sport_062', 'Hány bábut kell ledönteni a tökéletes bowlingban?', '[{"key":"A","text":"8","correct":false},{"key":"B","text":"10","correct":true},{"key":"C","text":"12","correct":false}]', 'B', 8, '{"A":10,"B":80,"C":10}', 'B', 'mixed'),
('sport_063', 'Melyik sportágban használnak ütőt és tollaslabdát?', '[{"key":"A","text":"Squash","correct":false},{"key":"B","text":"Tollaslabda","correct":true},{"key":"C","text":"Tenisz","correct":false}]', 'B', 8, '{"A":15,"B":75,"C":10}', 'B', 'mixed'),
('sport_064', 'Hány perc egy félidő a kézilabdában?', '[{"key":"A","text":"25","correct":false},{"key":"B","text":"30","correct":true},{"key":"C","text":"35","correct":false}]', 'B', 8, '{"A":20,"B":65,"C":15}', 'B', 'mixed'),
('sport_065', 'Melyik sportágban van Grand Slam?', '[{"key":"A","text":"Golf","correct":false},{"key":"B","text":"Tenisz","correct":true},{"key":"C","text":"Krikett","correct":false}]', 'B', 8, '{"A":15,"B":75,"C":10}', 'B', 'mixed'),
('sport_066', 'Ki nyerte a legtöbb Forma-1-es világbajnokságot?', '[{"key":"A","text":"Michael Schumacher","correct":false},{"key":"B","text":"Lewis Hamilton","correct":true},{"key":"C","text":"Ayrton Senna","correct":false}]', 'B', 8, '{"A":35,"B":55,"C":10}', 'B', 'mixed'),
('sport_067', 'Hány játékos van egy baseball csapatban a pályán?', '[{"key":"A","text":"8","correct":false},{"key":"B","text":"9","correct":true},{"key":"C","text":"10","correct":false}]', 'B', 8, '{"A":25,"B":60,"C":15}', 'B', 'mixed'),
('sport_068', 'Melyik sportágban van a Super Bowl döntő?', '[{"key":"A","text":"Baseball","correct":false},{"key":"B","text":"Amerikai futball","correct":true},{"key":"C","text":"Kosárlabda","correct":false}]', 'B', 8, '{"A":10,"B":80,"C":10}', 'B', 'mixed'),
('sport_069', 'Hány pont egy hárompontos kosárlabdában?', '[{"key":"A","text":"2","correct":false},{"key":"B","text":"3","correct":true},{"key":"C","text":"4","correct":false}]', 'B', 8, '{"A":10,"B":85,"C":5}', 'B', 'mixed'),
('sport_070', 'Melyik városban rendezték a 2008-as nyári olimpiát?', '[{"key":"A","text":"Athén","correct":false},{"key":"B","text":"Peking","correct":true},{"key":"C","text":"London","correct":false}]', 'B', 8, '{"A":15,"B":75,"C":10}', 'B', 'mixed'),
('sport_071', 'Mi a neve a golfban a par alatti két ütésnek?', '[{"key":"A","text":"Birdie","correct":false},{"key":"B","text":"Eagle","correct":true},{"key":"C","text":"Bogey","correct":false}]', 'B', 8, '{"A":35,"B":50,"C":15}', 'B', 'mixed'),
('sport_072', 'Hány periódusból áll egy jégkorongmérkőzés?', '[{"key":"A","text":"2","correct":false},{"key":"B","text":"3","correct":true},{"key":"C","text":"4","correct":false}]', 'B', 8, '{"A":20,"B":65,"C":15}', 'B', 'mixed'),
('sport_073', 'Melyik sportágban van a Masters torna?', '[{"key":"A","text":"Tenisz","correct":false},{"key":"B","text":"Golf","correct":true},{"key":"C","text":"Snooker","correct":false}]', 'B', 8, '{"A":20,"B":60,"C":20}', 'B', 'mixed'),
('sport_074', 'Hány km egy maraton?', '[{"key":"A","text":"40 km","correct":false},{"key":"B","text":"42,195 km","correct":true},{"key":"C","text":"45 km","correct":false}]', 'B', 8, '{"A":20,"B":70,"C":10}', 'B', 'mixed'),
('sport_075', 'Melyik sportágban használnak labdát és biliárdasztalt?', '[{"key":"A","text":"Snooker","correct":true},{"key":"B","text":"Darts","correct":false},{"key":"C","text":"Bowls","correct":false}]', 'A', 8, '{"A":75,"B":15,"C":10}', 'A', 'mixed');

-- Topic 8 fordítások (sport_051 - sport_075)
INSERT INTO question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c) VALUES
('sport_051', 'hu', 'Melyik csapat nyerte a legtöbb NBA bajnoki címet?', 'Los Angeles Lakers', 'Boston Celtics', 'Chicago Bulls'),
('sport_051', 'en', 'Which team has won the most NBA championships?', 'Los Angeles Lakers', 'Boston Celtics', 'Chicago Bulls'),
('sport_052', 'hu', 'Hány pont egy touchdown az amerikai futballban?', '5', '6', '7'),
('sport_052', 'en', 'How many points is a touchdown in American football?', '5', '6', '7'),
('sport_053', 'hu', 'Melyik országban rendezték az első téli olimpiát?', 'Svájc', 'Franciaország', 'Ausztria'),
('sport_053', 'en', 'In which country was the first Winter Olympics held?', 'Switzerland', 'France', 'Austria'),
('sport_054', 'hu', 'Hány lyukból áll egy standard golf pálya?', '16', '18', '20'),
('sport_054', 'en', 'How many holes are on a standard golf course?', '16', '18', '20'),
('sport_055', 'hu', 'Melyik sportágban használnak puck-ot?', 'Jégkorong', 'Floorball', 'Gyeplabda'),
('sport_055', 'en', 'In which sport is a puck used?', 'Ice hockey', 'Floorball', 'Field hockey'),
('sport_056', 'hu', 'Ki a valaha volt leggyorsabb futó a 100 méteren?', 'Carl Lewis', 'Usain Bolt', 'Justin Gatlin'),
('sport_056', 'en', 'Who is the fastest 100m runner ever?', 'Carl Lewis', 'Usain Bolt', 'Justin Gatlin'),
('sport_057', 'hu', 'Hány játékos van egy röplabdacsapatban a pályán?', '5', '6', '7'),
('sport_057', 'en', 'How many players are on a volleyball team on the court?', '5', '6', '7'),
('sport_058', 'hu', 'Melyik sportágban versenyeznek a Tour de France-on?', 'Futás', 'Kerékpározás', 'Triatlon'),
('sport_058', 'en', 'In which sport do competitors race in the Tour de France?', 'Running', 'Cycling', 'Triathlon'),
('sport_059', 'hu', 'Hány félidőből áll egy kosárlabda mérkőzés?', '2', '4', '3'),
('sport_059', 'en', 'How many quarters are in a basketball game?', '2', '4', '3'),
('sport_060', 'hu', 'Melyik országból származik a sumo birkózás?', 'Kína', 'Japán', 'Korea'),
('sport_060', 'en', 'Which country does sumo wrestling originate from?', 'China', 'Japan', 'Korea'),
('sport_061', 'hu', 'Mi a neve a teniszben a 40-40 állásnak?', 'Egyenlítés', 'Deuce', 'Advantage'),
('sport_061', 'en', 'What is the name for a 40-40 score in tennis?', 'Tie', 'Deuce', 'Advantage'),
('sport_062', 'hu', 'Hány bábut kell ledönteni a tökéletes bowlingban?', '8', '10', '12'),
('sport_062', 'en', 'How many pins need to be knocked down for a perfect bowling strike?', '8', '10', '12'),
('sport_063', 'hu', 'Melyik sportágban használnak ütőt és tollaslabdát?', 'Squash', 'Tollaslabda', 'Tenisz'),
('sport_063', 'en', 'In which sport is a racket and shuttlecock used?', 'Squash', 'Badminton', 'Tennis'),
('sport_064', 'hu', 'Hány perc egy félidő a kézilabdában?', '25', '30', '35'),
('sport_064', 'en', 'How many minutes is one half in handball?', '25', '30', '35'),
('sport_065', 'hu', 'Melyik sportágban van Grand Slam?', 'Golf', 'Tenisz', 'Krikett'),
('sport_065', 'en', 'In which sport is there a Grand Slam?', 'Golf', 'Tennis', 'Cricket'),
('sport_066', 'hu', 'Ki nyerte a legtöbb Forma-1-es világbajnokságot?', 'Michael Schumacher', 'Lewis Hamilton', 'Ayrton Senna'),
('sport_066', 'en', 'Who has won the most Formula 1 World Championships?', 'Michael Schumacher', 'Lewis Hamilton', 'Ayrton Senna'),
('sport_067', 'hu', 'Hány játékos van egy baseball csapatban a pályán?', '8', '9', '10'),
('sport_067', 'en', 'How many players are on a baseball team on the field?', '8', '9', '10'),
('sport_068', 'hu', 'Melyik sportágban van a Super Bowl döntő?', 'Baseball', 'Amerikai futball', 'Kosárlabda'),
('sport_068', 'en', 'In which sport is the Super Bowl final?', 'Baseball', 'American football', 'Basketball'),
('sport_069', 'hu', 'Hány pont egy hárompontos kosárlabdában?', '2', '3', '4'),
('sport_069', 'en', 'How many points is a three-pointer in basketball?', '2', '3', '4'),
('sport_070', 'hu', 'Melyik városban rendezték a 2008-as nyári olimpiát?', 'Athén', 'Peking', 'London'),
('sport_070', 'en', 'In which city were the 2008 Summer Olympics held?', 'Athens', 'Beijing', 'London'),
('sport_071', 'hu', 'Mi a neve a golfban a par alatti két ütésnek?', 'Birdie', 'Eagle', 'Bogey'),
('sport_071', 'en', 'What is the name for two under par in golf?', 'Birdie', 'Eagle', 'Bogey'),
('sport_072', 'hu', 'Hány periódusból áll egy jégkorongmérkőzés?', '2', '3', '4'),
('sport_072', 'en', 'How many periods are in an ice hockey game?', '2', '3', '4'),
('sport_073', 'hu', 'Melyik sportágban van a Masters torna?', 'Tenisz', 'Golf', 'Snooker'),
('sport_073', 'en', 'In which sport is the Masters tournament?', 'Tennis', 'Golf', 'Snooker'),
('sport_074', 'hu', 'Hány km egy maraton?', '40 km', '42,195 km', '45 km'),
('sport_074', 'en', 'How long is a marathon?', '40 km', '42.195 km', '45 km'),
('sport_075', 'hu', 'Melyik sportágban használnak labdát és biliárdasztalt?', 'Snooker', 'Darts', 'Bowls'),
('sport_075', 'en', 'In which sport are balls and a billiard table used?', 'Snooker', 'Darts', 'Bowls')
ON CONFLICT (question_id, lang) DO NOTHING;