-- Topic 11 (Földrajz) - 50 új kérdés (geo_151 - geo_200)
INSERT INTO questions (id, question, answers, correct_answer, topic_id, audience, third, source_category) VALUES
('geo_151', 'Mi a világ legnagyobb országa területileg?', '[{"key":"A","text":"Kanada","correct":false},{"key":"B","text":"Oroszország","correct":true},{"key":"C","text":"Kína","correct":false}]', 'B', 11, '{"A":15,"B":75,"C":10}', 'B', 'mixed'),
('geo_152', 'Melyik a világ leghosszabb folyója?', '[{"key":"A","text":"Amazonas","correct":false},{"key":"B","text":"Nílus","correct":true},{"key":"C","text":"Mississippi","correct":false}]', 'B', 11, '{"A":35,"B":50,"C":15}', 'B', 'mixed'),
('geo_153', 'Mi Ausztrália fővárosa?', '[{"key":"A","text":"Sydney","correct":false},{"key":"B","text":"Canberra","correct":true},{"key":"C","text":"Melbourne","correct":false}]', 'B', 11, '{"A":40,"B":45,"C":15}', 'B', 'mixed'),
('geo_154', 'Melyik a világ legmagasabb hegye?', '[{"key":"A","text":"K2","correct":false},{"key":"B","text":"Mount Everest","correct":true},{"key":"C","text":"Kangchenjunga","correct":false}]', 'B', 11, '{"A":10,"B":85,"C":5}', 'B', 'mixed'),
('geo_155', 'Hány kontinens van a Földön?', '[{"key":"A","text":"6","correct":false},{"key":"B","text":"7","correct":true},{"key":"C","text":"8","correct":false}]', 'B', 11, '{"A":20,"B":70,"C":10}', 'B', 'mixed'),
('geo_156', 'Mi Japán fővárosa?', '[{"key":"A","text":"Oszaka","correct":false},{"key":"B","text":"Tokió","correct":true},{"key":"C","text":"Kiotó","correct":false}]', 'B', 11, '{"A":10,"B":85,"C":5}', 'B', 'mixed'),
('geo_157', 'Melyik a világ legnagyobb óceánja?', '[{"key":"A","text":"Atlanti","correct":false},{"key":"B","text":"Csendes","correct":true},{"key":"C","text":"Indiai","correct":false}]', 'B', 11, '{"A":20,"B":70,"C":10}', 'B', 'mixed'),
('geo_158', 'Mi Brazília fővárosa?', '[{"key":"A","text":"Rio de Janeiro","correct":false},{"key":"B","text":"Brazíliaváros","correct":true},{"key":"C","text":"São Paulo","correct":false}]', 'B', 11, '{"A":35,"B":45,"C":20}', 'B', 'mixed'),
('geo_159', 'Melyik országban található a Taj Mahal?', '[{"key":"A","text":"Pakisztán","correct":false},{"key":"B","text":"India","correct":true},{"key":"C","text":"Banglades","correct":false}]', 'B', 11, '{"A":10,"B":85,"C":5}', 'B', 'mixed'),
('geo_160', 'Mi Kanada fővárosa?', '[{"key":"A","text":"Toronto","correct":false},{"key":"B","text":"Ottawa","correct":true},{"key":"C","text":"Vancouver","correct":false}]', 'B', 11, '{"A":35,"B":50,"C":15}', 'B', 'mixed'),
('geo_161', 'Melyik a világ legnagyobb sivataga?', '[{"key":"A","text":"Szahara","correct":false},{"key":"B","text":"Antarktisz","correct":true},{"key":"C","text":"Góbi","correct":false}]', 'B', 11, '{"A":55,"B":30,"C":15}', 'B', 'mixed'),
('geo_162', 'Mi Törökország fővárosa?', '[{"key":"A","text":"Isztambul","correct":false},{"key":"B","text":"Ankara","correct":true},{"key":"C","text":"Izmir","correct":false}]', 'B', 11, '{"A":45,"B":45,"C":10}', 'B', 'mixed'),
('geo_163', 'Melyik országban található a Viktória-vízesés?', '[{"key":"A","text":"Kenya","correct":false},{"key":"B","text":"Zimbabwe/Zambia","correct":true},{"key":"C","text":"Tanzánia","correct":false}]', 'B', 11, '{"A":25,"B":50,"C":25}', 'B', 'mixed'),
('geo_164', 'Mi Svájc fővárosa?', '[{"key":"A","text":"Zürich","correct":false},{"key":"B","text":"Bern","correct":true},{"key":"C","text":"Genf","correct":false}]', 'B', 11, '{"A":40,"B":45,"C":15}', 'B', 'mixed'),
('geo_165', 'Hány óceán van a Földön?', '[{"key":"A","text":"4","correct":false},{"key":"B","text":"5","correct":true},{"key":"C","text":"6","correct":false}]', 'B', 11, '{"A":25,"B":55,"C":20}', 'B', 'mixed'),
('geo_166', 'Mi Egyiptom fővárosa?', '[{"key":"A","text":"Alexandria","correct":false},{"key":"B","text":"Kairó","correct":true},{"key":"C","text":"Luxor","correct":false}]', 'B', 11, '{"A":15,"B":75,"C":10}', 'B', 'mixed'),
('geo_167', 'Melyik a világ legnépesebb országa?', '[{"key":"A","text":"Kína","correct":false},{"key":"B","text":"India","correct":true},{"key":"C","text":"USA","correct":false}]', 'B', 11, '{"A":40,"B":50,"C":10}', 'B', 'mixed'),
('geo_168', 'Mi Dél-Korea fővárosa?', '[{"key":"A","text":"Puszan","correct":false},{"key":"B","text":"Szöul","correct":true},{"key":"C","text":"Incshon","correct":false}]', 'B', 11, '{"A":15,"B":75,"C":10}', 'B', 'mixed'),
('geo_169', 'Melyik országban található a Machu Picchu?', '[{"key":"A","text":"Chile","correct":false},{"key":"B","text":"Peru","correct":true},{"key":"C","text":"Bolívia","correct":false}]', 'B', 11, '{"A":15,"B":70,"C":15}', 'B', 'mixed'),
('geo_170', 'Mi Németország fővárosa?', '[{"key":"A","text":"München","correct":false},{"key":"B","text":"Berlin","correct":true},{"key":"C","text":"Frankfurt","correct":false}]', 'B', 11, '{"A":10,"B":85,"C":5}', 'B', 'mixed'),
('geo_171', 'Melyik a világ legmélyebb tava?', '[{"key":"A","text":"Tanganyika-tó","correct":false},{"key":"B","text":"Bajkál-tó","correct":true},{"key":"C","text":"Kaszpi-tenger","correct":false}]', 'B', 11, '{"A":25,"B":55,"C":20}', 'B', 'mixed'),
('geo_172', 'Mi Mexikó fővárosa?', '[{"key":"A","text":"Cancún","correct":false},{"key":"B","text":"Mexikóváros","correct":true},{"key":"C","text":"Guadalajara","correct":false}]', 'B', 11, '{"A":10,"B":80,"C":10}', 'B', 'mixed'),
('geo_173', 'Melyik a világ legkisebb országa?', '[{"key":"A","text":"Monaco","correct":false},{"key":"B","text":"Vatikán","correct":true},{"key":"C","text":"San Marino","correct":false}]', 'B', 11, '{"A":25,"B":60,"C":15}', 'B', 'mixed'),
('geo_174', 'Mi Lengyelország fővárosa?', '[{"key":"A","text":"Krakkó","correct":false},{"key":"B","text":"Varsó","correct":true},{"key":"C","text":"Gdańsk","correct":false}]', 'B', 11, '{"A":20,"B":70,"C":10}', 'B', 'mixed'),
('geo_175', 'Melyik országban található a Grand Canyon?', '[{"key":"A","text":"Kanada","correct":false},{"key":"B","text":"USA","correct":true},{"key":"C","text":"Mexikó","correct":false}]', 'B', 11, '{"A":5,"B":90,"C":5}', 'B', 'mixed'),
('geo_176', 'Mi Argentína fővárosa?', '[{"key":"A","text":"Cordoba","correct":false},{"key":"B","text":"Buenos Aires","correct":true},{"key":"C","text":"Mendoza","correct":false}]', 'B', 11, '{"A":10,"B":80,"C":10}', 'B', 'mixed'),
('geo_177', 'Melyik a világ leghosszabb hegylánca?', '[{"key":"A","text":"Himalája","correct":false},{"key":"B","text":"Andok","correct":true},{"key":"C","text":"Sziklás-hegység","correct":false}]', 'B', 11, '{"A":35,"B":45,"C":20}', 'B', 'mixed'),
('geo_178', 'Mi Hollandia fővárosa?', '[{"key":"A","text":"Rotterdam","correct":false},{"key":"B","text":"Amszterdam","correct":true},{"key":"C","text":"Hága","correct":false}]', 'B', 11, '{"A":10,"B":80,"C":10}', 'B', 'mixed'),
('geo_179', 'Melyik országban található az Akropolisz?', '[{"key":"A","text":"Törökország","correct":false},{"key":"B","text":"Görögország","correct":true},{"key":"C","text":"Olaszország","correct":false}]', 'B', 11, '{"A":10,"B":80,"C":10}', 'B', 'mixed'),
('geo_180', 'Mi Thaiföld fővárosa?', '[{"key":"A","text":"Phuket","correct":false},{"key":"B","text":"Bangkok","correct":true},{"key":"C","text":"Chiang Mai","correct":false}]', 'B', 11, '{"A":10,"B":85,"C":5}', 'B', 'mixed'),
('geo_181', 'Melyik folyó folyik keresztül Párizson?', '[{"key":"A","text":"Rajna","correct":false},{"key":"B","text":"Szajna","correct":true},{"key":"C","text":"Loire","correct":false}]', 'B', 11, '{"A":20,"B":65,"C":15}', 'B', 'mixed'),
('geo_182', 'Mi Portugália fővárosa?', '[{"key":"A","text":"Porto","correct":false},{"key":"B","text":"Lisszabon","correct":true},{"key":"C","text":"Faro","correct":false}]', 'B', 11, '{"A":20,"B":70,"C":10}', 'B', 'mixed'),
('geo_183', 'Melyik országban található a Stonehenge?', '[{"key":"A","text":"Írország","correct":false},{"key":"B","text":"Anglia","correct":true},{"key":"C","text":"Skócia","correct":false}]', 'B', 11, '{"A":15,"B":70,"C":15}', 'B', 'mixed'),
('geo_184', 'Mi Ausztria fővárosa?', '[{"key":"A","text":"Salzburg","correct":false},{"key":"B","text":"Bécs","correct":true},{"key":"C","text":"Innsbruck","correct":false}]', 'B', 11, '{"A":10,"B":85,"C":5}', 'B', 'mixed'),
('geo_185', 'Melyik a világ legnagyobb szigete?', '[{"key":"A","text":"Madagaszkár","correct":false},{"key":"B","text":"Grönland","correct":true},{"key":"C","text":"Borneó","correct":false}]', 'B', 11, '{"A":20,"B":65,"C":15}', 'B', 'mixed'),
('geo_186', 'Mi Norvégia fővárosa?', '[{"key":"A","text":"Bergen","correct":false},{"key":"B","text":"Oslo","correct":true},{"key":"C","text":"Trondheim","correct":false}]', 'B', 11, '{"A":20,"B":70,"C":10}', 'B', 'mixed'),
('geo_187', 'Melyik országban található a Kilimandzsáró?', '[{"key":"A","text":"Kenya","correct":false},{"key":"B","text":"Tanzánia","correct":true},{"key":"C","text":"Uganda","correct":false}]', 'B', 11, '{"A":35,"B":50,"C":15}', 'B', 'mixed'),
('geo_188', 'Mi Svédország fővárosa?', '[{"key":"A","text":"Göteborg","correct":false},{"key":"B","text":"Stockholm","correct":true},{"key":"C","text":"Malmö","correct":false}]', 'B', 11, '{"A":15,"B":75,"C":10}', 'B', 'mixed'),
('geo_189', 'Melyik a világ legszélesebb folyója?', '[{"key":"A","text":"Nílus","correct":false},{"key":"B","text":"Amazonas","correct":true},{"key":"C","text":"Jangce","correct":false}]', 'B', 11, '{"A":25,"B":55,"C":20}', 'B', 'mixed'),
('geo_190', 'Mi Finnország fővárosa?', '[{"key":"A","text":"Turku","correct":false},{"key":"B","text":"Helsinki","correct":true},{"key":"C","text":"Tampere","correct":false}]', 'B', 11, '{"A":15,"B":75,"C":10}', 'B', 'mixed'),
('geo_191', 'Melyik országban található a Colosseum?', '[{"key":"A","text":"Görögország","correct":false},{"key":"B","text":"Olaszország","correct":true},{"key":"C","text":"Spanyolország","correct":false}]', 'B', 11, '{"A":10,"B":85,"C":5}', 'B', 'mixed'),
('geo_192', 'Mi Dánia fővárosa?', '[{"key":"A","text":"Aarhus","correct":false},{"key":"B","text":"Koppenhága","correct":true},{"key":"C","text":"Odense","correct":false}]', 'B', 11, '{"A":15,"B":75,"C":10}', 'B', 'mixed'),
('geo_193', 'Melyik óceán határolja Európát nyugatról?', '[{"key":"A","text":"Csendes","correct":false},{"key":"B","text":"Atlanti","correct":true},{"key":"C","text":"Indiai","correct":false}]', 'B', 11, '{"A":10,"B":80,"C":10}', 'B', 'mixed'),
('geo_194', 'Mi Belgium fővárosa?', '[{"key":"A","text":"Antwerpen","correct":false},{"key":"B","text":"Brüsszel","correct":true},{"key":"C","text":"Brugge","correct":false}]', 'B', 11, '{"A":15,"B":75,"C":10}', 'B', 'mixed'),
('geo_195', 'Melyik országban található a Nagy-korallzátony?', '[{"key":"A","text":"Új-Zéland","correct":false},{"key":"B","text":"Ausztrália","correct":true},{"key":"C","text":"Indonézia","correct":false}]', 'B', 11, '{"A":15,"B":75,"C":10}', 'B', 'mixed'),
('geo_196', 'Mi Írország fővárosa?', '[{"key":"A","text":"Cork","correct":false},{"key":"B","text":"Dublin","correct":true},{"key":"C","text":"Galway","correct":false}]', 'B', 11, '{"A":10,"B":80,"C":10}', 'B', 'mixed'),
('geo_197', 'Melyik a legdélibb kontinens?', '[{"key":"A","text":"Ausztrália","correct":false},{"key":"B","text":"Antarktisz","correct":true},{"key":"C","text":"Dél-Amerika","correct":false}]', 'B', 11, '{"A":15,"B":75,"C":10}', 'B', 'mixed'),
('geo_198', 'Mi Csehország fővárosa?', '[{"key":"A","text":"Brno","correct":false},{"key":"B","text":"Prága","correct":true},{"key":"C","text":"Ostrava","correct":false}]', 'B', 11, '{"A":10,"B":85,"C":5}', 'B', 'mixed'),
('geo_199', 'Melyik országban található a Fuji-hegy?', '[{"key":"A","text":"Kína","correct":false},{"key":"B","text":"Japán","correct":true},{"key":"C","text":"Korea","correct":false}]', 'B', 11, '{"A":10,"B":85,"C":5}', 'B', 'mixed'),
('geo_200', 'Mi Görögország fővárosa?', '[{"key":"A","text":"Thesszaloníki","correct":false},{"key":"B","text":"Athén","correct":true},{"key":"C","text":"Kréta","correct":false}]', 'B', 11, '{"A":10,"B":85,"C":5}', 'B', 'mixed');

-- Topic 11 fordítások
INSERT INTO question_translations (question_id, lang, question_text, answer_a, answer_b, answer_c) VALUES
('geo_151', 'hu', 'Mi a világ legnagyobb országa területileg?', 'Kanada', 'Oroszország', 'Kína'),
('geo_151', 'en', 'What is the largest country in the world by area?', 'Canada', 'Russia', 'China'),
('geo_152', 'hu', 'Melyik a világ leghosszabb folyója?', 'Amazonas', 'Nílus', 'Mississippi'),
('geo_152', 'en', 'Which is the longest river in the world?', 'Amazon', 'Nile', 'Mississippi'),
('geo_153', 'hu', 'Mi Ausztrália fővárosa?', 'Sydney', 'Canberra', 'Melbourne'),
('geo_153', 'en', 'What is the capital of Australia?', 'Sydney', 'Canberra', 'Melbourne'),
('geo_154', 'hu', 'Melyik a világ legmagasabb hegye?', 'K2', 'Mount Everest', 'Kangchenjunga'),
('geo_154', 'en', 'Which is the highest mountain in the world?', 'K2', 'Mount Everest', 'Kangchenjunga'),
('geo_155', 'hu', 'Hány kontinens van a Földön?', '6', '7', '8'),
('geo_155', 'en', 'How many continents are there on Earth?', '6', '7', '8'),
('geo_156', 'hu', 'Mi Japán fővárosa?', 'Oszaka', 'Tokió', 'Kiotó'),
('geo_156', 'en', 'What is the capital of Japan?', 'Osaka', 'Tokyo', 'Kyoto'),
('geo_157', 'hu', 'Melyik a világ legnagyobb óceánja?', 'Atlanti', 'Csendes', 'Indiai'),
('geo_157', 'en', 'Which is the largest ocean in the world?', 'Atlantic', 'Pacific', 'Indian'),
('geo_158', 'hu', 'Mi Brazília fővárosa?', 'Rio de Janeiro', 'Brazíliaváros', 'São Paulo'),
('geo_158', 'en', 'What is the capital of Brazil?', 'Rio de Janeiro', 'Brasilia', 'São Paulo'),
('geo_159', 'hu', 'Melyik országban található a Taj Mahal?', 'Pakisztán', 'India', 'Banglades'),
('geo_159', 'en', 'In which country is the Taj Mahal located?', 'Pakistan', 'India', 'Bangladesh'),
('geo_160', 'hu', 'Mi Kanada fővárosa?', 'Toronto', 'Ottawa', 'Vancouver'),
('geo_160', 'en', 'What is the capital of Canada?', 'Toronto', 'Ottawa', 'Vancouver'),
('geo_161', 'hu', 'Melyik a világ legnagyobb sivataga?', 'Szahara', 'Antarktisz', 'Góbi'),
('geo_161', 'en', 'Which is the largest desert in the world?', 'Sahara', 'Antarctica', 'Gobi'),
('geo_162', 'hu', 'Mi Törökország fővárosa?', 'Isztambul', 'Ankara', 'Izmir'),
('geo_162', 'en', 'What is the capital of Turkey?', 'Istanbul', 'Ankara', 'Izmir'),
('geo_163', 'hu', 'Melyik országban található a Viktória-vízesés?', 'Kenya', 'Zimbabwe/Zambia', 'Tanzánia'),
('geo_163', 'en', 'In which country is Victoria Falls located?', 'Kenya', 'Zimbabwe/Zambia', 'Tanzania'),
('geo_164', 'hu', 'Mi Svájc fővárosa?', 'Zürich', 'Bern', 'Genf'),
('geo_164', 'en', 'What is the capital of Switzerland?', 'Zurich', 'Bern', 'Geneva'),
('geo_165', 'hu', 'Hány óceán van a Földön?', '4', '5', '6'),
('geo_165', 'en', 'How many oceans are there on Earth?', '4', '5', '6'),
('geo_166', 'hu', 'Mi Egyiptom fővárosa?', 'Alexandria', 'Kairó', 'Luxor'),
('geo_166', 'en', 'What is the capital of Egypt?', 'Alexandria', 'Cairo', 'Luxor'),
('geo_167', 'hu', 'Melyik a világ legnépesebb országa?', 'Kína', 'India', 'USA'),
('geo_167', 'en', 'Which is the most populous country in the world?', 'China', 'India', 'USA'),
('geo_168', 'hu', 'Mi Dél-Korea fővárosa?', 'Puszan', 'Szöul', 'Incshon'),
('geo_168', 'en', 'What is the capital of South Korea?', 'Busan', 'Seoul', 'Incheon'),
('geo_169', 'hu', 'Melyik országban található a Machu Picchu?', 'Chile', 'Peru', 'Bolívia'),
('geo_169', 'en', 'In which country is Machu Picchu located?', 'Chile', 'Peru', 'Bolivia'),
('geo_170', 'hu', 'Mi Németország fővárosa?', 'München', 'Berlin', 'Frankfurt'),
('geo_170', 'en', 'What is the capital of Germany?', 'Munich', 'Berlin', 'Frankfurt'),
('geo_171', 'hu', 'Melyik a világ legmélyebb tava?', 'Tanganyika-tó', 'Bajkál-tó', 'Kaszpi-tenger'),
('geo_171', 'en', 'Which is the deepest lake in the world?', 'Lake Tanganyika', 'Lake Baikal', 'Caspian Sea'),
('geo_172', 'hu', 'Mi Mexikó fővárosa?', 'Cancún', 'Mexikóváros', 'Guadalajara'),
('geo_172', 'en', 'What is the capital of Mexico?', 'Cancun', 'Mexico City', 'Guadalajara'),
('geo_173', 'hu', 'Melyik a világ legkisebb országa?', 'Monaco', 'Vatikán', 'San Marino'),
('geo_173', 'en', 'Which is the smallest country in the world?', 'Monaco', 'Vatican City', 'San Marino'),
('geo_174', 'hu', 'Mi Lengyelország fővárosa?', 'Krakkó', 'Varsó', 'Gdańsk'),
('geo_174', 'en', 'What is the capital of Poland?', 'Krakow', 'Warsaw', 'Gdansk'),
('geo_175', 'hu', 'Melyik országban található a Grand Canyon?', 'Kanada', 'USA', 'Mexikó'),
('geo_175', 'en', 'In which country is the Grand Canyon located?', 'Canada', 'USA', 'Mexico'),
('geo_176', 'hu', 'Mi Argentína fővárosa?', 'Cordoba', 'Buenos Aires', 'Mendoza'),
('geo_176', 'en', 'What is the capital of Argentina?', 'Cordoba', 'Buenos Aires', 'Mendoza'),
('geo_177', 'hu', 'Melyik a világ leghosszabb hegylánca?', 'Himalája', 'Andok', 'Sziklás-hegység'),
('geo_177', 'en', 'Which is the longest mountain range in the world?', 'Himalayas', 'Andes', 'Rocky Mountains'),
('geo_178', 'hu', 'Mi Hollandia fővárosa?', 'Rotterdam', 'Amszterdam', 'Hága'),
('geo_178', 'en', 'What is the capital of Netherlands?', 'Rotterdam', 'Amsterdam', 'The Hague'),
('geo_179', 'hu', 'Melyik országban található az Akropolisz?', 'Törökország', 'Görögország', 'Olaszország'),
('geo_179', 'en', 'In which country is the Acropolis located?', 'Turkey', 'Greece', 'Italy'),
('geo_180', 'hu', 'Mi Thaiföld fővárosa?', 'Phuket', 'Bangkok', 'Chiang Mai'),
('geo_180', 'en', 'What is the capital of Thailand?', 'Phuket', 'Bangkok', 'Chiang Mai'),
('geo_181', 'hu', 'Melyik folyó folyik keresztül Párizson?', 'Rajna', 'Szajna', 'Loire'),
('geo_181', 'en', 'Which river flows through Paris?', 'Rhine', 'Seine', 'Loire'),
('geo_182', 'hu', 'Mi Portugália fővárosa?', 'Porto', 'Lisszabon', 'Faro'),
('geo_182', 'en', 'What is the capital of Portugal?', 'Porto', 'Lisbon', 'Faro'),
('geo_183', 'hu', 'Melyik országban található a Stonehenge?', 'Írország', 'Anglia', 'Skócia'),
('geo_183', 'en', 'In which country is Stonehenge located?', 'Ireland', 'England', 'Scotland'),
('geo_184', 'hu', 'Mi Ausztria fővárosa?', 'Salzburg', 'Bécs', 'Innsbruck'),
('geo_184', 'en', 'What is the capital of Austria?', 'Salzburg', 'Vienna', 'Innsbruck'),
('geo_185', 'hu', 'Melyik a világ legnagyobb szigete?', 'Madagaszkár', 'Grönland', 'Borneó'),
('geo_185', 'en', 'Which is the largest island in the world?', 'Madagascar', 'Greenland', 'Borneo'),
('geo_186', 'hu', 'Mi Norvégia fővárosa?', 'Bergen', 'Oslo', 'Trondheim'),
('geo_186', 'en', 'What is the capital of Norway?', 'Bergen', 'Oslo', 'Trondheim'),
('geo_187', 'hu', 'Melyik országban található a Kilimandzsáró?', 'Kenya', 'Tanzánia', 'Uganda'),
('geo_187', 'en', 'In which country is Mount Kilimanjaro located?', 'Kenya', 'Tanzania', 'Uganda'),
('geo_188', 'hu', 'Mi Svédország fővárosa?', 'Göteborg', 'Stockholm', 'Malmö'),
('geo_188', 'en', 'What is the capital of Sweden?', 'Gothenburg', 'Stockholm', 'Malmo'),
('geo_189', 'hu', 'Melyik a világ legszélesebb folyója?', 'Nílus', 'Amazonas', 'Jangce'),
('geo_189', 'en', 'Which is the widest river in the world?', 'Nile', 'Amazon', 'Yangtze'),
('geo_190', 'hu', 'Mi Finnország fővárosa?', 'Turku', 'Helsinki', 'Tampere'),
('geo_190', 'en', 'What is the capital of Finland?', 'Turku', 'Helsinki', 'Tampere'),
('geo_191', 'hu', 'Melyik országban található a Colosseum?', 'Görögország', 'Olaszország', 'Spanyolország'),
('geo_191', 'en', 'In which country is the Colosseum located?', 'Greece', 'Italy', 'Spain'),
('geo_192', 'hu', 'Mi Dánia fővárosa?', 'Aarhus', 'Koppenhága', 'Odense'),
('geo_192', 'en', 'What is the capital of Denmark?', 'Aarhus', 'Copenhagen', 'Odense'),
('geo_193', 'hu', 'Melyik óceán határolja Európát nyugatról?', 'Csendes', 'Atlanti', 'Indiai'),
('geo_193', 'en', 'Which ocean borders Europe to the west?', 'Pacific', 'Atlantic', 'Indian'),
('geo_194', 'hu', 'Mi Belgium fővárosa?', 'Antwerpen', 'Brüsszel', 'Brugge'),
('geo_194', 'en', 'What is the capital of Belgium?', 'Antwerp', 'Brussels', 'Bruges'),
('geo_195', 'hu', 'Melyik országban található a Nagy-korallzátony?', 'Új-Zéland', 'Ausztrália', 'Indonézia'),
('geo_195', 'en', 'In which country is the Great Barrier Reef located?', 'New Zealand', 'Australia', 'Indonesia'),
('geo_196', 'hu', 'Mi Írország fővárosa?', 'Cork', 'Dublin', 'Galway'),
('geo_196', 'en', 'What is the capital of Ireland?', 'Cork', 'Dublin', 'Galway'),
('geo_197', 'hu', 'Melyik a legdélibb kontinens?', 'Ausztrália', 'Antarktisz', 'Dél-Amerika'),
('geo_197', 'en', 'Which is the southernmost continent?', 'Australia', 'Antarctica', 'South America'),
('geo_198', 'hu', 'Mi Csehország fővárosa?', 'Brno', 'Prága', 'Ostrava'),
('geo_198', 'en', 'What is the capital of Czech Republic?', 'Brno', 'Prague', 'Ostrava'),
('geo_199', 'hu', 'Melyik országban található a Fuji-hegy?', 'Kína', 'Japán', 'Korea'),
('geo_199', 'en', 'In which country is Mount Fuji located?', 'China', 'Japan', 'Korea'),
('geo_200', 'hu', 'Mi Görögország fővárosa?', 'Thesszaloníki', 'Athén', 'Kréta'),
('geo_200', 'en', 'What is the capital of Greece?', 'Thessaloniki', 'Athens', 'Crete')
ON CONFLICT (question_id, lang) DO NOTHING;